import React, { createContext, useContext, useState, useEffect } from 'react';

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', region: 'National / Official' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', region: 'North & Central India' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', region: 'Karnataka' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', region: 'Tamil Nadu & Puducherry' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', region: 'Andhra Pradesh & Telangana' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', region: 'Kerala & Lakshadweep' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', region: 'Maharashtra & Goa' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', region: 'Gujarat & Daman/Diu' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', region: 'West Bengal & Tripura' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', region: 'Odisha' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', region: 'Punjab' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', region: 'Assam & North East' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', region: 'Jammu & Kashmir, Telangana, UP' }
];

const DICTIONARY = {
  en: {
    brandTagline: 'GOV PORTAL',
    brandSubtitle: 'Public Services & Grievance Governance',
    searchPlaceholder: 'Search grievances, service IDs, or FAQs...',
    citizenPortal: 'Citizen',
    adminPortal: 'Official Admin',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    createAccount: 'Create Account',
    lodgeGrievance: 'Lodge Grievance',
    overviewTab: 'Dashboard Overview',
    servicesTab: 'Public Services Catalog',
    trackTab: 'Track Status & Resolution',
    faqsTab: 'Knowledge Base & AI Guide',
    slaCompliance: 'SLA Compliance Rate',
    resolvedThisMonth: 'Cases Resolved This Month',
    totalLodged: 'Total Lodged',
    inProgress: 'In Progress',
    resolvedCases: 'Successfully Resolved',
    urgentAlerts: 'Urgent Alerts',
    popularServices: 'Popular Public Services',
    applyNow: 'Apply Now',
    recentSubmissions: 'Grievance Tracking & Redressal Stream',
    allWards: 'All Wards',
    mySubmissions: 'My Submissions',
    allStatuses: 'All Statuses',
    trackProgress: 'Track Progress & Timeline',
    needEscalation: 'Need Immediate Escalation?',
    helpline: '24x7 Citizen Helpline: 1800-425-GOV',
    nodalOfficerControl: 'Nodal Officer Control Dashboard',
    publicGovernanceCenter: 'Public Service Delivery Governance Center',
    governanceSubtitle: 'Real-time grievance routing, officer dispatch, SLA tracking, and resolution oversight.',
    exportCSV: 'Export CSV Summary Report',
    exportAudit: 'Print Audit Summary',
    awaitingReview: 'Awaiting Review',
    activeInField: 'Active In Field',
    urgentEscalations: 'Urgent Escalations',
    departmentWorkload: 'Department Grievance Workload Breakdown',
    slaTatScorecard: 'Department SLA Turnaround Time (TAT) Scorecard',
    manageTickets: 'Manage Grievance Tickets',
    manageTicketsSub: 'Assign officers, update status, inspect IPFS evidence, and attach official resolution notes',
    serviceAppsQueue: 'Citizen Public Service Applications Queue',
    serviceAppsQueueSub: 'Review citizen welfare applications, verify identity proofs, and issue approvals',
    grievancesQueue: 'Grievance Tickets Queue',
    serviceApps: 'Public Service Applications',
    kbTitle: 'Citizen Knowledge Base & FAQs',
    kbSubtitle: 'Official guidelines, SLA timelines, and procedure documents',
    aiBotTitle: 'JanSeva AI Assistant',
    aiBotSub: 'Instant 24x7 Help Bot',
    aiGreeting: 'Namaste! I am JanSeva AI Assistant. Ask me anything about citizen service SLAs, required documents, or paste your Ticket ID to look up live status!',
    askAiPlaceholder: 'Ask AI e.g. How long does a birth certificate take?',
    quickPrompt1: 'How do I track my grievance?',
    quickPrompt2: 'What documents are needed for a Birth Certificate?',
    quickPrompt3: 'What is the SLA deadline for Drainage overflow?',
    quickPrompt4: 'How do I re-open an unresolved ticket?',
    trackTitle: 'Live Grievance Redressal & SLA Tracking',
    trackSubtitle: 'Real-time timeline tracking, officer dispatch status, IPFS evidence, and Hyperledger blockchain verification',
    enterTrackingId: 'Enter Grievance Reference ID (e.g. GRV-2026-8910)',
    trackButton: 'Track Status',
    timelineHeader: 'Official Redressal Timeline',
    ipfsProof: 'IPFS Evidence Document',
    blockchainProof: 'Hyperledger Fabric Verification',
    citizenFeedback: 'Citizen Redressal Feedback',
    rateResolution: 'Rate your resolution experience',
    submitFeedback: 'Submit Feedback',
    reopenTicket: 'Issue Not Fixed? Re-open Ticket',
    printReceipt: 'Print Official Acknowledgment Receipt',
    settingsTitle: 'Portal Settings & Preferences',
    settingsSubtitle: 'Customize your regional language, notifications, accessibility, and profile',
    profileTab: 'Profile',
    languageTab: 'Language & State',
    appearanceTab: 'Appearance & A11y',
    alertsTab: 'Alerts & SMS',
    securityTab: 'Security',
    saveChanges: 'Save Changes',
    close: 'Close',
    notifications: 'Notifications',
    clearAll: 'Clear All',
    noNotifications: 'No new notifications',
    heroTitle: 'Citizen Service Delivery & Grievance Redressal',
    heroDesc: 'Transparent, accountable, and SLA-bound public service fulfillment for every citizen. Lodge complaints, apply for official certificates, and monitor real-time officer progress.',
    browseServices: 'Browse Public Services',
    viewAllServices: 'View All Services',
    fee: 'Fee',
    free: 'Free',
    daysSla: 'Days SLA',
    stageSubmitted: 'Submitted',
    stageReview: 'Under Review',
    stageAssigned: 'Assigned',
    stageProgress: 'In Progress',
    stageResolved: 'Resolved',
    langName: 'English'
  },
  hi: {
    brandTagline: 'सरकारी पोर्टल',
    brandSubtitle: 'सार्वजनिक सेवा वितरण एवं नागरिक शिकायत निवारण प्रणाली',
    searchPlaceholder: 'शिकायत, सेवा आईडी या प्रश्न खोजें...',
    citizenPortal: 'नागरिक पोर्टल',
    adminPortal: 'अधिकारी नियंत्रण कक्ष',
    signIn: 'लॉग इन करें',
    signOut: 'लॉग आउट',
    createAccount: 'खाता बनाएं',
    lodgeGrievance: 'नई शिकायत दर्ज करें',
    overviewTab: 'डैशबोर्ड अवलोकन',
    servicesTab: 'सार्वजनिक सेवाएँ',
    trackTab: 'स्थिति और समाधान ट्रैक करें',
    faqsTab: 'सहायता एवं एआई गाइड',
    slaCompliance: 'एसएलए अनुपालन दर',
    resolvedThisMonth: 'इस माह हल किए गए मामले',
    totalLodged: 'कुल दर्ज शिकायतें',
    inProgress: 'प्रगति पर',
    resolvedCases: 'सफलतापूर्वक हल',
    urgentAlerts: 'आपातकालीन अलर्ट',
    popularServices: 'लोकप्रिय सार्वजनिक सेवाएँ',
    applyNow: 'आवेदन करें',
    recentSubmissions: 'नागरिक शिकायत निवारण सूची',
    allWards: 'सभी वार्ड',
    mySubmissions: 'मेरी शिकायतें',
    allStatuses: 'सभी स्थितियाँ',
    trackProgress: 'स्थिति और समयरेखा देखें',
    needEscalation: 'तत्काल सहायता चाहिए?',
    helpline: '24x7 नागरिक हेल्पलाइन: 1800-425-GOV',
    nodalOfficerControl: 'नोडल अधिकारी नियंत्रण कक्ष',
    publicGovernanceCenter: 'लोक सेवा वितरण एवं शासन केंद्र',
    governanceSubtitle: 'वास्तविक समय शिकायत रूटिंग, अधिकारी प्रेषण, एसएलए ट्रैकिंग और समाधान निरीक्षण।',
    exportCSV: 'सीएसवी सारांश रिपोर्ट निर्यात करें',
    exportAudit: 'ऑडिट सारांश प्रिंट करें',
    awaitingReview: 'समीक्षाधीन',
    activeInField: 'फील्ड में सक्रिय',
    urgentEscalations: 'अति आवश्यक मामले',
    departmentWorkload: 'विभागवार शिकायत कार्यभार विवरण',
    slaTatScorecard: 'विभागीय एसएलए टर्नअराउंड समय (टीएटी) स्कोरकार्ड',
    manageTickets: 'शिकायत टिकट प्रबंधित करें',
    manageTicketsSub: 'अधिकारी नियुक्त करें, स्थिति अपडेट करें, आईपीएफएस साक्ष्य जांचें और आधिकारिक नोट जोड़ें',
    serviceAppsQueue: 'नागरिक लोक सेवा आवेदन कतार',
    serviceAppsQueueSub: 'नागरिक कल्याण आवेदनों की समीक्षा करें और स्वीकृतियां जारी करें',
    grievancesQueue: 'शिकायत टिकट कतार',
    serviceApps: 'लोक सेवा आवेदन',
    kbTitle: 'नागरिक ज्ञानकोष एवं अक्सर पूछे जाने वाले प्रश्न',
    kbSubtitle: 'आधिकारिक दिशानिर्देश, एसएलए समयसीमा और प्रक्रिया दस्तावेज',
    aiBotTitle: 'जनसेवा एआई सहायक',
    aiBotSub: 'तत्काल 24x7 सहायता बॉट',
    aiGreeting: 'नमस्ते! मैं जनसेवा एआई सहायक हूँ। नागरिक सेवा एसएलए, आवश्यक दस्तावेजों के बारे में पूछें या अपनी शिकायत आईडी दर्ज करें!',
    askAiPlaceholder: 'एआई से पूछें (उदा. जन्म प्रमाण पत्र में कितना समय लगता है?)',
    quickPrompt1: 'मैं अपनी शिकायत कैसे ट्रैक करूं?',
    quickPrompt2: 'जन्म प्रमाण पत्र के लिए कौन से दस्तावेज चाहिए?',
    quickPrompt3: 'जलभराव या नाली की समस्या का एसएलए क्या है?',
    quickPrompt4: 'असमाधानित शिकायत को दोबारा कैसे खोलें?',
    trackTitle: 'लाइव शिकायत निवारण एवं एसएलए ट्रैकिंग',
    trackSubtitle: 'वास्तविक समय समयरेखा, अधिकारी प्रेषण, आईपीएफएस साक्ष्य और ब्लॉकचेन सत्यापन',
    enterTrackingId: 'शिकायत संदर्भ संख्या दर्ज करें (उदा. GRV-2026-8910)',
    trackButton: 'स्थिति जांचें',
    timelineHeader: 'आधिकारिक निवारण समयरेखा',
    ipfsProof: 'आईपीएफएस साक्ष्य दस्तावेज',
    blockchainProof: 'हाइपरलेजर फैब्रिक ब्लॉकचेन सत्यापन',
    citizenFeedback: 'नागरिक निवारण प्रतिक्रिया',
    rateResolution: 'समाधान अनुभव का मूल्यांकन करें',
    submitFeedback: 'प्रतिक्रिया जमा करें',
    reopenTicket: 'समस्या हल नहीं हुई? शिकायत पुनः खोलें',
    printReceipt: 'आधिकारिक पावती रसीद प्रिंट करें',
    settingsTitle: 'पोर्टल सेटिंग्स एवं प्राथमिकताएं',
    settingsSubtitle: 'अपनी क्षेत्रीय भाषा, सूचनाएं, सुगमता और प्रोफ़ाइल अनुकूलित करें',
    profileTab: 'प्रोफ़ाइल',
    languageTab: 'भाषा एवं राज्य',
    appearanceTab: 'दिखावट एवं सुगमता',
    alertsTab: 'अलर्ट एवं एसएमएस',
    securityTab: 'सुरक्षा',
    saveChanges: 'परिवर्तन सहेजें',
    close: 'बंद करें',
    notifications: 'सूचनाएं',
    clearAll: 'सभी हटाएं',
    noNotifications: 'कोई नई सूचना नहीं',
    heroTitle: 'नागरिक सेवा वितरण एवं शिकायत निवारण',
    heroDesc: 'हर नागरिक के लिए पारदर्शी, जवाबदेह और एसएलए-बाध्य सार्वजनिक सेवा वितरण। शिकायतें दर्ज करें और अधिकारी की प्रगति ट्रैक करें।',
    browseServices: 'सार्वजनिक सेवाएं देखें',
    viewAllServices: 'सभी सेवाएं देखें',
    fee: 'शुल्क',
    free: 'निःशुल्क',
    daysSla: 'दिन एसएलए',
    stageSubmitted: 'दर्ज किया गया',
    stageReview: 'समीक्षाधीन',
    stageAssigned: 'नियुक्त किया गया',
    stageProgress: 'प्रगति पर',
    stageResolved: 'सफलतापूर्वक हल',
    langName: 'हिन्दी'
  },
  kn: {
    brandTagline: 'ಸರ್ಕಾರಿ ಪೋರ್ಟಲ್',
    brandSubtitle: 'ಸಾರ್ವಜನಿಕ ಸೇವಾ ವಿತರಣೆ ಮತ್ತು ನಾಗರಿಕ ಕುಂದುಕೊರತೆ ನಿರ್ವಹಣೆ',
    searchPlaceholder: 'ದೂರುಗಳು, ಸೇವಾ ಐಡಿ ಅಥವಾ ಪ್ರಶ್ನೆಗಳನ್ನು ಹುಡುಕಿ...',
    citizenPortal: 'ನಾಗರಿಕ ಪೋರ್ಟಲ್',
    adminPortal: 'ಅಧಿಕಾರಿ ನಿಯಂತ್ರಣ ಕೊಠಡಿ',
    signIn: 'ಸೈನ್ ಇನ್',
    signOut: 'ಸೈನ್ ಔಟ್',
    createAccount: 'ಖಾತೆ ತೆರೆಯಿರಿ',
    lodgeGrievance: 'ಹೊಸ ದೂರು ದಾಖಲಿಸಿ',
    overviewTab: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಅವಲೋಕನ',
    servicesTab: 'ಸಾರ್ವಜನಿಕ ಸೇವೆಗಳು',
    trackTab: 'ಸ್ಥಿತಿ ಮತ್ತು ಪ್ರಗತಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    faqsTab: 'ಸಹಾಯ ಮತ್ತು AI ಮಾರ್ಗದರ್ಶಿ',
    slaCompliance: 'SLA ಅನುಸರಣಾ ದರ',
    resolvedThisMonth: 'ಈ ತಿಂಗಳು ಪರಿಹರಿಸಲಾದ ಪ್ರಕರಣಗಳು',
    totalLodged: 'ಒಟ್ಟು ದಾಖಲಾದ ದೂರುಗಳು',
    inProgress: 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    resolvedCases: 'ಯಶಸ್ವಿಯಾಗಿ ಪರಿಹರಿಸಲಾಗಿದೆ',
    urgentAlerts: 'ತುರ್ತು ಎಚ್ಚರಿಕೆಗಳು',
    popularServices: 'ಜನಪ್ರಿಯ ಸಾರ್ವಜನಿಕ ಸೇವೆಗಳು',
    applyNow: 'ಈಗಲೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    recentSubmissions: 'ದೂರುಗಳ ಟ್ರ್ಯಾಕಿಂಗ್ ಪಟ್ಟಿ',
    allWards: 'ಎಲ್ಲಾ ವಾರ್ಡ್‌ಗಳು',
    mySubmissions: 'ನನ್ನ ದೂರುಗಳು',
    allStatuses: 'ಎಲ್ಲಾ ಸ್ಥಿತಿಗಳು',
    trackProgress: 'ಪ್ರಗತಿ ಮತ್ತು ಸಮಯರೇಖೆಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    needEscalation: 'ತುರ್ತು ಸಹಾಯ ಬೇಕೇ?',
    helpline: '24x7 ನಾಗರಿಕ ಸಹಾಯವಾಣಿ: 1800-425-GOV',
    nodalOfficerControl: 'ನೋಡಲ್ ಅಧಿಕಾರಿ ನಿಯಂತ್ರಣ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    publicGovernanceCenter: 'ಸಾರ್ವಜನಿಕ ಸೇವಾ ವಿತರಣಾ ಆಡಳಿತ ಕೇಂದ್ರ',
    governanceSubtitle: 'ನೈಜ-ಸಮಯದ ದೂರು ವರ್ಗಾವಣೆ, ಅಧಿಕಾರಿ ನಿಯೋಜನೆ ಮತ್ತು SLA ಪರಿಹಾರ ಮೇಲ್ವಿಚಾರಣೆ.',
    exportCSV: 'CSV ಸಾರಾಂಶ ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    exportAudit: 'ಆಡಿಟ್ ಸಾರಾಂಶ ಮುದ್ರಿಸಿ',
    awaitingReview: 'ಪರಿಶೀಲನೆಗಾಗಿ ಕಾಯುತ್ತಿದೆ',
    activeInField: 'ಕ್ಷೇತ್ರದಲ್ಲಿ ಸಕ್ರಿಯವಾಗಿದೆ',
    urgentEscalations: 'ತುರ್ತು ಪ್ರಕರಣಗಳು',
    departmentWorkload: 'ಇಲಾಖಾವಾರು ದೂರುಗಳ ಕಾರ್ಯಭಾರ ವಿವರ',
    slaTatScorecard: 'ಇಲಾಖಾ SLA ಟರ್ನ್‌ಅರೌಂಡ್ ಸಮಯ (TAT) ಸ್ಕೋರ್‌ಕಾರ್ಡ್',
    manageTickets: 'ದೂರು ಟಿಕೆಟ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    manageTicketsSub: 'ಅಧಿಕಾರಿಗಳನ್ನು ನಿಯೋಜಿಸಿ, ಸ್ಥಿತಿ ನವೀಕರಿಸಿ ಮತ್ತು IPFS ಪುರಾವೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    serviceAppsQueue: 'ಸಾರ್ವಜನಿಕ ಸೇವಾ ಅರ್ಜಿಗಳ ಸಾಲು',
    serviceAppsQueueSub: 'ನಾಗರಿಕ ಅರ್ಜಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಡಿಜಿಟಲ್ ಪ್ರಮಾಣಪತ್ರಗಳನ್ನು ನೀಡಿ',
    grievancesQueue: 'ದೂರುಗಳ ಟಿಕೆಟ್ ಸಾಲು',
    serviceApps: 'ಸಾರ್ವಜನಿಕ ಸೇವಾ ಅರ್ಜಿಗಳು',
    kbTitle: 'ನಾಗರಿಕ ಜ್ಞಾನಕೋಶ ಮತ್ತು ಪ್ರಶ್ನೋತ್ತರಗಳು',
    kbSubtitle: 'ಅಧಿಕೃತ ಮಾರ್ಗಸೂಚಿಗಳು, SLA ಕಾಲಮಿತಿ ಮತ್ತು ನಿಯಮಾವಳಿಗಳು',
    aiBotTitle: 'ಜನಸೇವಾ AI ಸಹಾಯಕ',
    aiBotSub: '24x7 ತ್ವರಿತ ಸಹಾಯ ಬಾಟ್',
    aiGreeting: 'ನಮಸ್ಕಾರ! ನಾನು ಜನಸೇವಾ AI ಸಹಾಯಕ. ಸೇವಾ SLA, ಅಗತ್ಯ ದಾಖಲೆಗಳು ಅಥವಾ ನಿಮ್ಮ ದೂರಿನ ಐಡಿ ನಮೂದಿಸಿ ನೇರ ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಿ!',
    askAiPlaceholder: 'AI ಗೆ ಪ್ರಶ್ನೆ ಕೇಳಿ (ಉದಾ: ಜನನ ಪ್ರಮಾಣಪತ್ರ ಪಡೆಯಲು ಎಷ್ಟು ದಿನ ಬೇಕು?)',
    quickPrompt1: 'ನನ್ನ ದೂರನ್ನು ಹೇಗೆ ಟ್ರ್ಯಾಕ್ ಮಾಡುವುದು?',
    quickPrompt2: 'ಜನನ ಪ್ರಮಾಣಪತ್ರಕ್ಕೆ ಯಾವ ದಾಖಲೆಗಳು ಬೇಕು?',
    quickPrompt3: 'ಒಳಚರಂಡಿ ಸಮಸ್ಯೆಗೆ SLA ಕಾಲಮಿತಿ ಏನು?',
    quickPrompt4: 'ಪರಿಹಾರವಾಗದ ದೂರನ್ನು ಮರುತೆರೆಯುವುದು ಹೇಗೆ?',
    trackTitle: 'ನೈಜ-ಸಮಯದ ದೂರು ಪರಿಹಾರ ಮತ್ತು SLA ಟ್ರ್ಯಾಕಿಂಗ್',
    trackSubtitle: 'ನೈಜ-ಸಮಯದ ಪ್ರಗತಿ, ನಿಯೋಜಿತ ಅಧಿಕಾರಿ ವಿವರ, IPFS ಪುರಾವೆ ಮತ್ತು ಬ್ಲಾಕ್‌ಚೈನ್ ಪರಿಶೀಲನೆ',
    enterTrackingId: 'ದೂರು ಟಿಕೆಟ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ (ಉದಾ: GRV-2026-8910)',
    trackButton: 'ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಿ',
    timelineHeader: 'ಅಧಿಕೃತ ಪರಿಹಾರ ಪ್ರಗತಿ ಪಟ್ಟಿ',
    ipfsProof: 'IPFS ಪುರಾವೆ ದಾಖಲೆ',
    blockchainProof: 'ಹೈಪರ್‌ಲೆಡ್ಜರ್ ಫ್ಯಾಬ್ರಿಕ್ ಬ್ಲಾಕ್‌ಚೈನ್ ದೃಢೀಕರಣ',
    citizenFeedback: 'ನಾಗರಿಕ ಪರಿಹಾರ ಪ್ರತಿಕ್ರಿಯೆ',
    rateResolution: 'ಪರಿಹಾರದ ಗುಣಮಟ್ಟವನ್ನು ರೇಟ್ ಮಾಡಿ',
    submitFeedback: 'ಪ್ರತಿಕ್ರಿಯೆ ಸಲ್ಲಿಸಿ',
    reopenTicket: 'ಸಮಸ್ಯೆ ಬಗೆಹರಿದಿಲ್ಲವೇ? ದೂರನ್ನು ಮರುತೆರೆಯಿರಿ',
    printReceipt: 'ಅಧಿಕೃತ ರಶೀದಿಯನ್ನು ಮುದ್ರಿಸಿ',
    settingsTitle: 'ಸೆಟ್ಟಿಂಗ್ಸ್ ಮತ್ತು ಆದ್ಯತೆಗಳು',
    settingsSubtitle: 'ಭಾಷೆ, ಅಧಿಸೂಚನೆಗಳು ಮತ್ತು ಪ್ರೊಫೈಲ್ ಕಸ್ಟಮೈಸ್ ಮಾಡಿ',
    profileTab: 'ಪ್ರೊಫೈಲ್',
    languageTab: 'ಭಾಷೆ ಮತ್ತು ರಾಜ್ಯ',
    appearanceTab: 'ಗೋಚರತೆ ಮತ್ತು ಸುಲಭತೆ',
    alertsTab: 'ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು SMS',
    securityTab: 'ಭದ್ರತೆ',
    saveChanges: 'ಬದಲಾವಣೆ ಉಳಿಸಿ',
    close: 'ಮುಚ್ಚಿ',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    clearAll: 'ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ',
    noNotifications: 'ಯಾವುದೇ ಹೊಸ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ',
    heroTitle: 'ಸಾರ್ವಜನಿಕ ಸೇವಾ ವಿತರಣೆ ಮತ್ತು ನಾಗರಿಕ ಕುಂದುಕೊರತೆ ಪರಿಹಾರ',
    heroDesc: 'ಪ್ರತಿಯೊಬ್ಬ ನಾಗರಿಕನಿಗೂ ಪಾರದರ್ಶಕ ಮತ್ತು ಜವಾಬ್ದಾರಿಯುತ ಸೇವಾ ವಿತರಣೆ. ದೂರು ದಾಖಲಿಸಿ ಮತ್ತು ಅಧಿಕಾರಿಯ ಪ್ರಗತಿ ವೀಕ್ಷಿಸಿ.',
    browseServices: 'ಸೇವೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    viewAllServices: 'ಎಲ್ಲಾ ಸೇವೆಗಳು',
    fee: 'ಶುಲ್ಕ',
    free: 'ಉಚಿತ',
    daysSla: 'ದಿನಗಳ SLA',
    stageSubmitted: 'ದಾಖಲಾಗಿದೆ',
    stageReview: 'ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ',
    stageAssigned: 'ನಿಯೋಜಿಸಲಾಗಿದೆ',
    stageProgress: 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    stageResolved: 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    langName: 'ಕನ್ನಡ'
  },
  ta: {
    brandTagline: 'அரசு போர்டல்',
    brandSubtitle: 'பொது சேவை வழங்கல் மற்றும் குடிமக்கள் குறைதீர்க்கும் மேலாண்மை',
    searchPlaceholder: 'புகார்கள், சேவை எண் அல்லது கேள்விகளைத் தேடுங்கள்...',
    citizenPortal: 'குடிமக்கள் போர்டல்',
    adminPortal: 'அதிகாரி கட்டுப்பாட்டு அறை',
    signIn: 'உள்நுழைக',
    signOut: 'வெளியேறு',
    createAccount: 'கணக்கை உருவாக்கவும்',
    lodgeGrievance: 'புதிய புகார் பதிவு செய்',
    overviewTab: 'டாஷ்போர்டு கண்ணோட்டம்',
    servicesTab: 'பொது சேவைகள் பட்டியல்',
    trackTab: 'நிலையைக் கண்காணிக்கவும்',
    faqsTab: 'உதவி மற்றும் AI வழிகாட்டி',
    slaCompliance: 'SLA இணக்க விகிதம்',
    resolvedThisMonth: 'இம்மாதம் தீர்க்கப்பட்ட புகார்கள்',
    totalLodged: 'மொத்த புகார்கள்',
    inProgress: 'நடவடிக்கையில் உள்ளது',
    resolvedCases: 'வெற்றிகரமாக தீர்க்கப்பட்டது',
    urgentAlerts: 'அவசர எச்சரிக்கைகள்',
    popularServices: 'பிரபலமான பொது சேவைகள்',
    applyNow: 'இப்போதே விண்ணப்பிக்கவும்',
    recentSubmissions: 'புகார் கண்காணிப்பு பட்டியல்',
    allWards: 'அனைத்து வார்டுகள்',
    mySubmissions: 'எனது புகார்கள்',
    allStatuses: 'அனைத்து நிலைகள்',
    trackProgress: 'முன்னேற்றத்தைக் கண்காணிக்கவும்',
    needEscalation: 'உடனடி உதவி தேவையா?',
    helpline: '24x7 குடிமக்கள் உதவி எண்: 1800-425-GOV',
    nodalOfficerControl: 'நோடல் அதிகாரி கட்டுப்பாட்டு மையம்',
    publicGovernanceCenter: 'பொது சேவை வழங்கல் ஆளுகை மையம்',
    governanceSubtitle: 'நிகழ்நேர புகார் பரிமாற்றம், அதிகாரி நியமனம் மற்றும் SLA தீர்வு கண்காணிப்பு.',
    exportCSV: 'CSV அறிக்கை பதிவிறக்கு',
    exportAudit: 'தணிக்கை அறிக்கை அச்சிடு',
    awaitingReview: 'பரிசீலனையில் உள்ளது',
    activeInField: 'களத்தில் செயலில் உள்ளது',
    urgentEscalations: 'அவசர புகார்கள்',
    departmentWorkload: 'துறைவாரி பணிச்சுமை விவரம்',
    slaTatScorecard: 'துறை SLA திருப்புமுனை நேர (TAT) அறிக்கை',
    manageTickets: 'புகார் டிக்கெட்டுகளை நிர்வகிக்கவும்',
    manageTicketsSub: 'அதிகாரிகளை நியமிக்கவும், நிலையை புதுப்பிக்கவும், IPFS ஆதாரங்களை சரிபார்க்கவும்',
    serviceAppsQueue: 'பொது சேவை விண்ணப்பங்கள் வரிசை',
    serviceAppsQueueSub: 'விண்ணப்பங்களை சரிபார்த்து டிஜிட்டல் சான்றிதழ்களை வழங்கவும்',
    grievancesQueue: 'புகார் டிக்கெட் வரிசை',
    serviceApps: 'பொது சேவை விண்ணப்பங்கள்',
    kbTitle: 'குடிமக்கள் வழிகாட்டி மற்றும் அடிக்கடி கேட்கப்படும் கேள்விகள்',
    kbSubtitle: 'அதிகாரப்பூர்வ வழிகாட்டுதல்கள் மற்றும் SLA காலக்கெடு',
    aiBotTitle: 'ஜன்சேவா AI உதவியாளர்',
    aiBotSub: '24x7 உடனடி உதவி பாட்',
    aiGreeting: 'வணக்கம்! நான் ஜன்சேவா AI உதவியாளர். சேவைகள் அல்லது உங்கள் புகார் எண்ணை பதிவிட்டு நிலையை அறியலாம்!',
    askAiPlaceholder: 'AI-யிடம் கேளுங்கள் (எ.கா: பிறப்பு சான்றிதழ் பெற எத்தனை நாட்கள் ஆகும்?)',
    quickPrompt1: 'எனது புகாரை எவ்வாறு கண்காணிப்பது?',
    quickPrompt2: 'பிறப்பு சான்றிதழுக்கு என்ன ஆவணங்கள் தேவை?',
    quickPrompt3: 'சாக்கடை பிரச்சனைக்கான SLA நேரம் என்ன?',
    quickPrompt4: 'தீர்க்கப்படாத புகாரை மீண்டும் திறப்பது எப்படி?',
    trackTitle: 'நேரடி புகார் தீர்வு மற்றும் SLA கண்காணிப்பு',
    trackSubtitle: 'நிகழ்நேர முன்னேற்றம், அதிகாரி விவரம் மற்றும் பிளாக்செயின் சான்றிதழ்',
    enterTrackingId: 'புகார் எண்ணை உள்ளிடவும் (எ.கா: GRV-2026-8910)',
    trackButton: 'நிலையைக் காண்க',
    timelineHeader: 'அதிகாரப்பூர்வ தீர்வு காலவரிசை',
    ipfsProof: 'IPFS ஆவண சான்று',
    blockchainProof: 'ஹைப்பர்லெட்ஜர் ஃபேப்ரிக் பிளாக்செயின் சரிபார்ப்பு',
    citizenFeedback: 'குடிமக்கள் தீர்வு கருத்து',
    rateResolution: 'தீர்வு திருப்தியை மதிப்பிடவும்',
    submitFeedback: 'கருத்தை சமர்ப்பிக்கவும்',
    reopenTicket: 'சிக்கல் தீரவில்லையா? புகாரை மீண்டும் திறக்கவும்',
    printReceipt: 'அதிகாரப்பூர்வ ரசீதை அச்சிடுக',
    settingsTitle: 'அமைப்புகள் மற்றும் விருப்பத்தேர்வுகள்',
    settingsSubtitle: 'மொழி, அறிவிப்புகள் மற்றும் சுயவிவரத்தை மாற்றவும்',
    profileTab: 'சுயவிவரம்',
    languageTab: 'மொழி மற்றும் மாநிலம்',
    appearanceTab: 'தோற்றம்',
    alertsTab: 'அறிவிப்புகள்',
    securityTab: 'பாதுகாப்பு',
    saveChanges: 'மாற்றங்களை சேமிக்கவும்',
    close: 'மூடு',
    notifications: 'அறிவிப்புகள்',
    clearAll: 'அனைத்தையும் அழிக்கவும்',
    noNotifications: 'புதிய அறிவிப்புகள் இல்லை',
    heroTitle: 'குடிமக்கள் சேவை வழங்கல் மற்றும் குறைதீர்ப்பு அமைப்பு',
    heroDesc: 'ஒவ்வொரு குடிமகனுக்கும் வெளிப்படையான பொது சேவை. புகார்களை பதிவு செய்து முன்னேற்றத்தைக் கண்காணிக்கவும்.',
    browseServices: 'சேவைகளை உலாவுக',
    viewAllServices: 'அனைத்து சேவைகளும்',
    fee: 'கட்டணம்',
    free: 'இலவசம்',
    daysSla: 'நாட்கள் SLA',
    stageSubmitted: 'சமர்ப்பிக்கப்பட்டது',
    stageReview: 'பரிசீலனையில்',
    stageAssigned: 'நியமிக்கப்பட்டது',
    stageProgress: 'நடவடிக்கையில்',
    stageResolved: 'தீர்க்கப்பட்டது',
    langName: 'தமிழ்'
  },
  te: {
    brandTagline: 'ప్రభుత్వ పోర్టల్',
    brandSubtitle: 'ప్రజా సేవల డెలివరీ మరియు పౌర ఫిర్యాదుల పరిష్కార వ్యవస్థ',
    searchPlaceholder: 'ఫిర్యాదులు, సేవా ఐడీ లేదా ప్రశ్నలను వెతకండి...',
    citizenPortal: 'పౌర పోర్టల్',
    adminPortal: 'అధికారి నియంత్రణ గది',
    signIn: 'సైన్ ఇన్',
    signOut: 'సైన్ అవుట్',
    createAccount: 'ఖాతా తెరవండి',
    lodgeGrievance: 'కొత్త ఫిర్యాదు నమోదు చేయండి',
    overviewTab: 'డాష్‌బోర్డ్ అవలోకనం',
    servicesTab: 'ప్రజా సేవల జాబితా',
    trackTab: 'స్థితి మరియు పరిష్కారాన్ని ట్రాక్ చేయండి',
    faqsTab: 'సహాయం మరియు AI గైడ్',
    slaCompliance: 'SLA సమ్మతి రేటు',
    resolvedThisMonth: 'ఈ నెలలో పరిష్కరించబడినవి',
    totalLodged: 'మొత్తం నమోదైనవి',
    inProgress: 'పురోగతిలో ఉంది',
    resolvedCases: 'విజయవంతంగా పరిష్కరించబడింది',
    urgentAlerts: 'అత్యవసర హెచ్చరికలు',
    popularServices: 'ప్రజాదరణ పొందిన సేవలు',
    applyNow: 'ఇప్పుడే దరఖాస్తు చేసుకోండి',
    recentSubmissions: 'ఫిర్యాదుల పర్యవేక్షణ జాబితా',
    allWards: 'అన్ని వార్డులు',
    mySubmissions: 'నా ఫిర్యాదులు',
    allStatuses: 'అన్ని స్థితులు',
    trackProgress: 'పురోగతిని ట్రాక్ చేయండి',
    needEscalation: 'తక్షణ సహాయం కావాలా?',
    helpline: '24x7 పౌర హెల్ప్‌లైన్: 1800-425-GOV',
    nodalOfficerControl: 'నోడల్ ఆఫీసర్ నియంత్రణ డాష్‌బోర్డ్',
    publicGovernanceCenter: 'ప్రజా సేవల డెలివరీ పాలనా కేంద్రం',
    governanceSubtitle: 'రియల్-టైమ్ ఫిర్యాదుల మళ్లింపు, అధికారి కేటాయింపు మరియు SLA పరిష్కార పర్యవేక్షణ.',
    exportCSV: 'CSV నివేదిక డౌన్‌లోడ్',
    exportAudit: 'ఆడిట్ నివేదిక ప్రింట్ చేయండి',
    awaitingReview: 'సమీక్ష కోసం వేచి ఉంది',
    activeInField: 'ఫీల్డ్‌లో క్రియాశీలంగా ఉంది',
    urgentEscalations: 'అత్యవసర కేసులు',
    departmentWorkload: 'విభాగాల వారీగా పనిభారం వివరాలు',
    slaTatScorecard: 'విభాగ SLA టర్నరౌండ్ సమయం (TAT) స్కోర్‌కార్డ్',
    manageTickets: 'ఫిర్యాదు టిక్కెట్లను నిర్వహించండి',
    manageTicketsSub: 'అధికారులను కేటాయించండి, స్థితిని నవీకరించండి, IPFS సాక్ష్యాలను తనిఖీ చేయండి',
    serviceAppsQueue: 'ప్రజా సేవల దరఖాస్తుల క్యూ',
    serviceAppsQueueSub: 'పౌర దరఖాస్తులను ధృవీకరించండి మరియు సర్టిఫికేట్లు జారీ చేయండి',
    grievancesQueue: 'ఫిర్యాదుల క్యూ',
    serviceApps: 'ప్రజా సేవల దరఖాస్తులు',
    kbTitle: 'పౌర సమాచార వేదిక మరియు ప్రశ్నలు',
    kbSubtitle: 'అధికారిక మార్గదర్శకాలు మరియు SLA కాలపరిమితులు',
    aiBotTitle: 'జనసేవ AI సహాయకుడు',
    aiBotSub: '24x7 తక్షణ సహాయం',
    aiGreeting: 'నమస్కారం! నేను జనసేవ AI సహాయకుడిని. సేవల వివరాలు లేదా మీ ఫిర్యాదు ఐడీని నమోదు చేసి స్థితిని తెలుసుకోండి!',
    askAiPlaceholder: 'AI ని అడగండి (ఉదా: జనన ధృవీకరణ పత్రం ఎప్పుడు వస్తుంది?)',
    quickPrompt1: 'నా ఫిర్యాదును ఎలా ట్రాక్ చేయాలి?',
    quickPrompt2: 'బర్త్ సర్టిఫికెట్ కోసం ఏ పత్రాలు అవసరం?',
    quickPrompt3: 'డ్రైనేజీ సమస్యకు SLA సమయం ఎంత?',
    quickPrompt4: 'పరిష్కారం కాని ఫిర్యాదును మళ్లీ ఎలా తెరవాలి?',
    trackTitle: 'లైవ్ ఫిర్యాదుల పరిష్కారం మరియు ట్రాకింగ్',
    trackSubtitle: 'రియల్ టైమ్ పురోగతి, అధికారి వివరాలు మరియు బ్లాక్‌చెయిన్ ధృవీకరణ',
    enterTrackingId: 'ఫిర్యాదు ఐడీని నమోదు చేయండి (ఉదా: GRV-2026-8910)',
    trackButton: 'స్థితిని చూడండి',
    timelineHeader: 'పరిష్కార కాలక్రమం',
    ipfsProof: 'IPFS సాక్ష్య పత్రం',
    blockchainProof: 'హైపర్‌లెడ్జర్ ఫ్యాబ్రిక్ ధృవీకరణ',
    citizenFeedback: 'పౌర అభిప్రాయం',
    rateResolution: 'సేవా అనుభవాన్ని రేట్ చేయండి',
    submitFeedback: 'అభిప్రాయాన్ని సమర్పించండి',
    reopenTicket: 'సమస్య పరిష్కారం కాలేదా? ఫిర్యాదును రీఓపెన్ చేయండి',
    printReceipt: 'రసీదును ప్రింట్ చేయండి',
    settingsTitle: 'సెట్టింగ్‌లు మరియు ప్రాధాన్యతలు',
    settingsSubtitle: 'భాష, నోటిఫికేషన్‌లు మరియు ప్రొఫైల్ మార్చుకోండి',
    profileTab: 'ప్రొఫైల్',
    languageTab: 'భాష మరియు రాష్ట్రం',
    appearanceTab: 'రూపం',
    alertsTab: 'హెచ్చరికలు',
    securityTab: 'భద్రత',
    saveChanges: 'మార్పులను సేవ్ చేయండి',
    close: 'మూసివేయి',
    notifications: 'నోటిఫికేషన్‌లు',
    clearAll: 'అన్నీ తొలగించు',
    noNotifications: 'కొత్త నోటిఫికేషన్‌లు లేవు',
    heroTitle: 'పౌర సేవల డెలివరీ మరియు ఫిర్యాదుల పరిష్కారం',
    heroDesc: 'పారదర్శకమైన మరియు జవాబుదారీతనంతో కూడిన ప్రజా సేవలు. ఫిర్యాదులను నమోదు చేయండి మరియు ట్రాక్ చేయండి.',
    browseServices: 'సేవలను బ్రౌజ్ చేయండి',
    viewAllServices: 'అన్ని సేవలు',
    fee: 'రుసుము',
    free: 'ఉచితం',
    daysSla: 'రోజుల SLA',
    stageSubmitted: 'నమోదైంది',
    stageReview: 'సమీక్షలో',
    stageAssigned: 'కేటాయించబడింది',
    stageProgress: 'పురోగతిలో',
    stageResolved: 'పరిష్కరించబడింది',
    langName: 'తెలుగు'
  },
  ml: {
    brandTagline: 'സർക്കാർ പോർട്ടൽ',
    brandSubtitle: 'പൊതു സേവന വിതരണവും പൗര പരാതി പരിഹാര സംവിധാനവും',
    searchPlaceholder: 'പരാതികൾ, സേവന ഐഡി അല്ലെങ്കിൽ ചോദ്യങ്ങൾ തിരയുക...',
    citizenPortal: 'പൗര പോർട്ടൽ',
    adminPortal: 'ഉദ്യോഗസ്ഥ നിയന്ത്രണ മുറി',
    signIn: 'സൈൻ ഇൻ ചെയ്യുക',
    signOut: 'സൈൻ ഔട്ട്',
    createAccount: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    lodgeGrievance: 'പരാതി രജിസ്റ്റർ ചെയ്യുക',
    overviewTab: 'ഡാഷ്‌ബോർഡ് അവലോകനം',
    servicesTab: 'പൊതു സേവനങ്ങൾ',
    trackTab: 'സ്ഥിതിഗതികൾ ട്രാക്ക് ചെയ്യുക',
    faqsTab: 'സഹായവും AI ഗൈഡും',
    slaCompliance: 'SLA പാലിക്കൽ നിരക്ക്',
    resolvedThisMonth: 'ഈ മാസം പരിഹരിച്ച കേസുകൾ',
    totalLodged: 'ആകെ ലഭിച്ച പരാതികൾ',
    inProgress: 'നടപടികൾ പുരോഗമിക്കുന്നു',
    resolvedCases: 'വിജയകരമായി പരിഹരിച്ചു',
    urgentAlerts: 'അടിയന്തര മുന്നറിയിപ്പുകൾ',
    popularServices: 'ജനപ്രിയ പൊതു സേവനങ്ങൾ',
    applyNow: 'ഇപ്പോൾ അപേക്ഷിക്കുക',
    recentSubmissions: 'പരാതി പരിഹാര പട്ടിക',
    allWards: 'എല്ലാ വാർഡുകളും',
    mySubmissions: 'എന്റെ പരാതികൾ',
    allStatuses: 'എല്ലാ നിലകളും',
    trackProgress: 'പുരോഗതി പരിശോധിക്കുക',
    needEscalation: 'അടിയന്തര സഹായം ആവശ്യമുണ്ടോ?',
    helpline: '24x7 പൗര ഹെൽപ്പ് ലൈൻ: 1800-425-GOV',
    nodalOfficerControl: 'നോഡൽ ഓഫീസർ കൺട്രോൾ ഡാഷ്‌ബോർഡ്',
    publicGovernanceCenter: 'പൊതുസേവന ഭരണ കേന്ദ്രം',
    governanceSubtitle: 'തത്സമയ പരാതി റൂട്ടിംഗ്, ഉദ്യോഗസ്ഥ നിയോഗം, SLA പരിഹാര മേൽനോട്ടം.',
    exportCSV: 'CSV റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക',
    exportAudit: 'ഓഡിറ്റ് റിപ്പോർട്ട് പ്രിന്റ് ചെയ്യുക',
    awaitingReview: 'പരിശോധനയിലാണ്',
    activeInField: 'ഫീൽഡിൽ സജീവം',
    urgentEscalations: 'അടിയന്തര പരാതികൾ',
    departmentWorkload: 'വകുപ്പ് തിരിച്ചുള്ള ജോലിഭാരം',
    slaTatScorecard: 'വകുപ്പ് SLA ടേൺഎറൗണ്ട് സമയം (TAT) സ്കോർകാർഡ്',
    manageTickets: 'പരാതി ടിക്കറ്റുകൾ കൈകാര്യം ചെയ്യുക',
    manageTicketsSub: 'ഉദ്യോഗസ്ഥരെ ചുമതലപ്പെടുത്തുക, സ്ഥിതി അപ്ഡേറ്റ് ചെയ്യുക, IPFS തെളിവുകൾ പരിശോധിക്കുക',
    serviceAppsQueue: 'സേവന അപേക്ഷകളുടെ ക്യൂ',
    serviceAppsQueueSub: 'അപേക്ഷകൾ പരിശോധിച്ച് ഡിജിറ്റൽ സർട്ടിഫിക്കറ്റുകൾ നൽകുക',
    grievancesQueue: 'പരാതി ടിക്കറ്റ് ക്യൂ',
    serviceApps: 'പൊതു സേവന അപേക്ഷകൾ',
    kbTitle: 'പൗര വിവര കേന്ദ്രവും ചോദ്യോത്തരങ്ങളും',
    kbSubtitle: 'ഔദ്യോഗിക മാർഗ്ഗനിർദ്ദേശങ്ങളും സമയപരിധികളും',
    aiBotTitle: 'ജനസേവ AI സഹായി',
    aiBotSub: '24x7 തത്സമയ സഹായം',
    aiGreeting: 'നമസ്കാരം! ഞാൻ ജനസേവ AI സഹായിയാണ്. സേവനങ്ങളെക്കുറിച്ചുള്ള വിവരങ്ങൾ അറിയാൻ ചോദിക്കൂ!',
    askAiPlaceholder: 'AI യോട് ചോദിക്കൂ (ഉദാ: ജനന സർട്ടിഫിക്കറ്റ് ലഭിക്കാൻ എത്ര ദിവസമെടുക്കും?)',
    quickPrompt1: 'എന്റെ പരാതി എങ്ങനെ ട്രാക്ക് ചെയ്യാം?',
    quickPrompt2: 'ജനന സർട്ടിഫിക്കറ്റിന് എന്തൊക്കെ രേഖകൾ വേണം?',
    quickPrompt3: 'ഓവുചാൽ പ്രശ്നങ്ങൾക്കുള്ള SLA സമയം എത്ര?',
    quickPrompt4: 'തീർപ്പുകൽപ്പിക്കാത്ത പരാതി എങ്ങനെ വീണ്ടും തുറക്കാം?',
    trackTitle: 'തത്സമയ പരാതി പരിഹാരവും ട്രാക്കിംഗും',
    trackSubtitle: 'തത്സമയ പുരോഗതിയും ബ്ലോക്ക്‌ചെയിൻ പരിശോധനയും',
    enterTrackingId: 'പരാതി ഐഡി നൽകുക (ഉദാ: GRV-2026-8910)',
    trackButton: 'സ്ഥിതി അറിയുക',
    timelineHeader: 'പരിഹാര പുരോഗതി ഘട്ടങ്ങൾ',
    ipfsProof: 'IPFS തെളിവ് രേഖ',
    blockchainProof: 'ഹൈപ്പർലെഡ്ജർ ഫാബ്രിക് പരിശോധന',
    citizenFeedback: 'പൗര അഭിപ്രായം',
    rateResolution: 'പരിഹാര അനുഭവം റേറ്റുചെയ്യുക',
    submitFeedback: 'അഭിപ്രായം സമർപ്പിക്കുക',
    reopenTicket: 'പ്രശ്നം പരിഹരിച്ചില്ലേ? പരാതി വീണ്ടും തുറക്കുക',
    printReceipt: 'രസീത് പ്രിന്റ് ചെയ്യുക',
    settingsTitle: 'ക്രമീകരണങ്ങളും മുൻഗണനകളും',
    settingsSubtitle: 'ഭാഷയും അറിയിപ്പുകളും മാറ്റുക',
    profileTab: 'പ്രൊഫൈൽ',
    languageTab: 'ഭാഷയും സംസ്ഥാനവും',
    appearanceTab: 'കാഴ്ച',
    alertsTab: 'അറിയിപ്പുകൾ',
    securityTab: 'സുരക്ഷ',
    saveChanges: 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക',
    close: 'അടയ്ക്കുക',
    notifications: 'അറിയിപ്പുകൾ',
    clearAll: 'എല്ലാം മായ്ക്കുക',
    noNotifications: 'പുതിയ അറിയിപ്പുകളൊന്നുമില്ല',
    heroTitle: 'പൊതു സേവന വിതരണവും പരാതി പരിഹാരവും',
    heroDesc: 'സുതാര്യവും ഉത്തരവാദിത്തമുള്ളതുമായ പൗര സേവനങ്ങൾ.',
    browseServices: 'സേവനങ്ങൾ കാണുക',
    viewAllServices: 'എല്ലാ സേവനങ്ങളും',
    fee: 'ഫീസ്',
    free: 'സൗജന്യം',
    daysSla: 'ദിവസം SLA',
    stageSubmitted: 'സമർപ്പിച്ചു',
    stageReview: 'പരിശോധനയിൽ',
    stageAssigned: 'നിയോഗിച്ചു',
    stageProgress: 'പുരോഗതിയിൽ',
    stageResolved: 'പരിഹരിച്ചു',
    langName: 'മലയാളം'
  },
  mr: {
    brandTagline: 'शासकीय पोर्टल',
    brandSubtitle: 'सार्वजनिक सेवा वितरण व नागरिक तक्रार निवारण प्रणाली',
    searchPlaceholder: 'तक्रार, सेवा आयडी किंवा प्रश्न शोधा...',
    citizenPortal: 'नागरिक पोर्टल',
    adminPortal: 'अधिकारी नियंत्रण कक्ष',
    signIn: 'साइन इन करा',
    signOut: 'साइन आउट',
    createAccount: 'खाते तयार करा',
    lodgeGrievance: 'नवीन तक्रार नोंदवा',
    overviewTab: 'डॅशबोर्ड विहंगावलोकन',
    servicesTab: 'सार्वजनिक सेवा सूची',
    trackTab: 'स्थिती व निवारण ट्रॅक करा',
    faqsTab: 'मदत व AI मार्गदर्शक',
    slaCompliance: 'SLA पूर्तता दर',
    resolvedThisMonth: 'या महिन्यात सोडवलेली प्रकरणे',
    totalLodged: 'एकूण नोंदवलेल्या तक्रारी',
    inProgress: 'प्रगतीपथावर',
    resolvedCases: 'यशस्वीरीत्या निवारण',
    urgentAlerts: 'तातडीच्या सूचना',
    popularServices: 'लोकप्रिय सार्वजनिक सेवा',
    applyNow: 'आता अर्ज करा',
    recentSubmissions: 'तक्रार निवारण प्रवाह',
    allWards: 'सर्व प्रभाग/वॉर्ड',
    mySubmissions: 'माझ्या तक्रारी',
    allStatuses: 'सर्व स्थिती',
    trackProgress: 'प्रगती व कालमर्यादा ट्रॅक करा',
    needEscalation: 'तातडीची मदत हवी आहे का?',
    helpline: '24x7 नागरिक हेल्पलाइन: 1800-425-GOV',
    nodalOfficerControl: 'नोडल अधिकारी नियंत्रण डॅशबोर्ड',
    publicGovernanceCenter: 'सार्वजनिक सेवा वितरण प्रशासन केंद्र',
    governanceSubtitle: 'रिअल-टाइम तक्रार वाटप, अधिकारी नियुक्ती आणि SLA निवारण पर्यवेक्षण.',
    exportCSV: 'CSV अहवाल डाउनलोड करा',
    exportAudit: 'ऑडिट अहवाल प्रिंट करा',
    awaitingReview: 'पुनरावलोकनाधीन',
    activeInField: 'फील्डवर सक्रिय',
    urgentEscalations: 'तातडीची प्रकरणे',
    departmentWorkload: 'विभागनिहाय तक्रार भार तपशील',
    slaTatScorecard: 'विभागीय SLA निवारण वेळ (TAT) स्कोअरकार्ड',
    manageTickets: 'तक्रार तिकिटे व्यवस्थापित करा',
    manageTicketsSub: 'अधिकारी नियुक्त करा, स्थिती अद्यतनित करा, IPFS पुरावे तपासा',
    serviceAppsQueue: 'सार्वजनिक सेवा अर्ज रांग',
    serviceAppsQueueSub: 'नागरिक अर्जांची पडताळणी करा आणि प्रमाणपत्रे जारी करा',
    grievancesQueue: 'तक्रार तिकिट रांग',
    serviceApps: 'सार्वजनिक सेवा अर्ज',
    kbTitle: 'नागरिक ज्ञानकोश आणि वारंवार विचारले जाणारे प्रश्न',
    kbSubtitle: 'अधिकृत मार्गदर्शक तत्त्वे आणि SLA कालमर्यादा',
    aiBotTitle: 'जनसेवा AI सहाय्यक',
    aiBotSub: '24x7 तत्पर मदत बॉट',
    aiGreeting: 'नमस्कार! मी जनसेवा AI सहाय्यक आहे. सेवांच्या माहितीसाठी विचारा किंवा तक्रार आयडी टाका!',
    askAiPlaceholder: 'AI ला विचारा (उदा: जन्म दाखला मिळण्यासाठी किती दिवस लागतात?)',
    quickPrompt1: 'माझी तक्रार कशी ट्रॅक करावी?',
    quickPrompt2: 'जन्म प्रमाणपत्रासाठी कोणती कागदपत्रे लागतात?',
    quickPrompt3: 'ड्रेनेज समस्येसाठी SLA वेळ किती आहे?',
    quickPrompt4: 'असमाधानकारक तक्रार पुन्हा कशी सुरू करावी?',
    trackTitle: 'थेट तक्रार निवारण आणि ट्रॅकिंग',
    trackSubtitle: 'रिअल-टाइम प्रगती आणि ब्लॉकचेन पडताळणी',
    enterTrackingId: 'तक्रार आयडी टाका (उदा: GRV-2026-8910)',
    trackButton: 'स्थिती पहा',
    timelineHeader: 'निवारण कालमर्यादा',
    ipfsProof: 'IPFS पुरावा दस्तऐवज',
    blockchainProof: 'हायपरलेजर फॅब्रिक पडताळणी',
    citizenFeedback: 'नागरिक अभिप्राय',
    rateResolution: 'निवारण गुणवत्तेला रेट करा',
    submitFeedback: 'अभिप्राय सबमिट करा',
    reopenTicket: 'समस्या सुटली नाही? तक्रार पुन्हा उघडा',
    printReceipt: 'पावती प्रिंट करा',
    settingsTitle: 'सेटिंग्ज आणि प्राधान्ये',
    settingsSubtitle: 'भाषा आणि सूचना बदला',
    profileTab: 'प्रोफाइल',
    languageTab: 'भाषा आणि राज्य',
    appearanceTab: 'स्वरूप',
    alertsTab: 'सूचना',
    securityTab: 'सुरक्षा',
    saveChanges: 'बदल जतन करा',
    close: 'बंद करा',
    notifications: 'सूचना',
    clearAll: 'सर्व साफ करा',
    noNotifications: 'नवीन सूचना नाहीत',
    heroTitle: 'सार्वजनिक सेवा वितरण आणि तक्रार निवारण',
    heroDesc: 'पारदर्शक आणि उत्तरदायी सार्वजनिक सेवा.',
    browseServices: 'सेवा शोधा',
    viewAllServices: 'सर्व सेवा',
    fee: 'शुल्क',
    free: 'मोफत',
    daysSla: 'दिवस SLA',
    stageSubmitted: 'दाखल केले',
    stageReview: 'पुनरावलोकनात',
    stageAssigned: 'नियुक्त केले',
    stageProgress: 'प्रगतीपथावर',
    stageResolved: 'निवारण झाले',
    langName: 'मराठी'
  },
  gu: {
    brandTagline: 'સરકારી પોર્ટલ',
    brandSubtitle: 'જાહેર સેવા વિતરણ અને નાગરિક ફરિયાદ નિવારણ વ્યવસ્થા',
    searchPlaceholder: 'ફરિયાદ, સેવા આઈડી અથવા પ્રશ્નો શોધો...',
    citizenPortal: 'નાગરિક પોર્ટલ',
    adminPortal: 'અધિકારી કંટ્રોલ રૂમ',
    signIn: 'સાઇન ઇન',
    signOut: 'સાઇન આઉટ',
    createAccount: 'ખાતું બનાવો',
    lodgeGrievance: 'નવી ફરિયાદ નોંધાવો',
    overviewTab: 'ડેશબોર્ડ ઝાંખી',
    servicesTab: 'જાહેર સેવાઓની યાદી',
    trackTab: 'સ્થિતિ અને નિવારણ ટ્રેક કરો',
    faqsTab: 'સહાય અને AI ગાઇડ',
    slaCompliance: 'SLA પાલન દર',
    resolvedThisMonth: 'આ મહિને ઉકેલાયેલા કેસો',
    totalLodged: 'કુલ નોંધાયેલ ફરિયાદો',
    inProgress: 'પ્રગતિ હેઠળ',
    resolvedCases: 'સફળતાપૂર્વક ઉકેલાયેલ',
    urgentAlerts: 'તાકીદની ચેતવણીઓ',
    popularServices: 'લોકપ્રિય જાહેર સેવાઓ',
    applyNow: 'હમણાં અરજી કરો',
    recentSubmissions: 'ફરિયાદ નિવારણ પ્રવાહ',
    allWards: 'બધા વોર્ડ',
    mySubmissions: 'મારી ફરિયાદો',
    allStatuses: 'બધી સ્થિતિઓ',
    trackProgress: 'પ્રગતિ અને સમયરેખા ટ્રેક કરો',
    needEscalation: 'તાત્કાલિક મદદની જરૂર છે?',
    helpline: '24x7 નાગરિક હેલ્પલાઇન: 1800-425-GOV',
    nodalOfficerControl: 'નોડલ ઓફિસર કંટ્રોલ ડેશબોર્ડ',
    publicGovernanceCenter: 'જાહેર સેવા વિતરણ શાસન કેન્દ્ર',
    governanceSubtitle: 'રીઅલ-ટાઇમ ફરિયાદ રૂટિંગ, અધિકારી નિમણૂક અને SLA ટ્રેકિંગ.',
    exportCSV: 'CSV અહેવાલ ડાઉનલોડ કરો',
    exportAudit: 'ઓડિટ રિપોર્ટ પ્રિન્ટ કરો',
    awaitingReview: 'સમીક્ષા હેઠળ',
    activeInField: 'ફીલ્ડમાં સક્રિય',
    urgentEscalations: 'તાકીદના કેસો',
    departmentWorkload: 'વિભાગવાર કાર્યભાર વિગત',
    slaTatScorecard: 'વિભાગીય SLA ટર્નઅરાઉન્ડ સમય (TAT) સ્કોરકાર્ડ',
    manageTickets: 'ફરિયાદ ટિકિટોનું સંચાલન કરો',
    manageTicketsSub: 'અધિકારીઓની નિમણૂક કરો, સ્થિતિ અપડેટ કરો, IPFS પુરાવા ચકાસો',
    serviceAppsQueue: 'જાહેર સેવા અરજીઓની કતાર',
    serviceAppsQueueSub: 'નાગરિક અરજીઓની ચકાસણી કરો અને પ્રમાણપત્રો જારી કરો',
    grievancesQueue: 'ફરિયાદ ટિકિટ કતાર',
    serviceApps: 'જાહેર સેવા અરજીઓ',
    kbTitle: 'નાગરિક માહિતી કેન્દ્ર અને પ્રશ્નોત્તરી',
    kbSubtitle: 'સત્તાવાર માર્ગદર્શિકા અને SLA સમયમર્યાદા',
    aiBotTitle: 'જનસેવા AI સહાયક',
    aiBotSub: '24x7 તાત્કાલિક સહાય બોટ',
    aiGreeting: 'નમસ્તે! હું જનસેવા AI સહાયક છું. સેવાઓની માહિતી માટે પૂછો અથવા ફરિયાદ આઈડી દાખલ કરો!',
    askAiPlaceholder: 'AI ને પૂછો (દા.ત: જન્મ પ્રમાણપત્ર મેળવવામાં કેટલો સમય લાગે?)',
    quickPrompt1: 'મારી ફરિયાદ કેવી રીતે ટ્રેક કરવી?',
    quickPrompt2: 'જન્મ પ્રમાણપત્ર માટે કયા દસ્તાવેજો જોઈએ?',
    quickPrompt3: 'ડ્રેનેજ સમસ્યા માટે SLA સમય કેટલો છે?',
    quickPrompt4: 'અણઉકેલાયેલ ફરિયાદ ફરીથી કેવી રીતે ખોલવી?',
    trackTitle: 'લાઇવ ફરિયાદ નિવારણ અને ટ્રેકિંગ',
    trackSubtitle: 'રીઅલ-ટાઇમ પ્રગતિ અને બ્લોકચેન ચકાસણી',
    enterTrackingId: 'ફરિયાદ આઈડી દાખલ કરો (દા.ત: GRV-2026-8910)',
    trackButton: 'સ્થિતિ જુઓ',
    timelineHeader: 'નિવારણ સમયરેખા',
    ipfsProof: 'IPFS પુરાવા દસ્તાવેજ',
    blockchainProof: 'હાયપરલેજર ફેબ્રિક ચકાસણી',
    citizenFeedback: 'નાગરિક પ્રતિસાદ',
    rateResolution: 'સેવા અનુભવને રેટ કરો',
    submitFeedback: 'પ્રતિસાદ સબમિટ કરો',
    reopenTicket: 'સમસ્યા હલ થઈ નથી? ફરિયાદ ફરી ખોલો',
    printReceipt: 'રસીદ પ્રિન્ટ કરો',
    settingsTitle: 'સેટિંગ્સ અને પસંદગીઓ',
    settingsSubtitle: 'ભાષા અને સૂચનાઓ બદલો',
    profileTab: 'પ્રોફાઇલ',
    languageTab: 'ભાષા અને રાજ્ય',
    appearanceTab: 'દેખાવ',
    alertsTab: 'સૂચનાઓ',
    securityTab: 'સુરક્ષા',
    saveChanges: 'ફેરફારો સાચવો',
    close: 'બંધ કરો',
    notifications: 'સૂચનાઓ',
    clearAll: 'બધું સાફ કરો',
    noNotifications: 'કોઈ નવી સૂચના નથી',
    heroTitle: 'જાહેર સેવા વિતરણ અને ફરિયાદ નિવારણ',
    heroDesc: 'પારદર્શક અને જવાબદાર જાહેર સેવાઓ.',
    browseServices: 'સેવાઓ જુઓ',
    viewAllServices: 'બધી સેવાઓ',
    fee: 'ફી',
    free: 'મફત',
    daysSla: 'દિવસો SLA',
    stageSubmitted: 'સબમિટ કરેલ',
    stageReview: 'સમીક્ષામાં',
    stageAssigned: 'સોંપેલ',
    stageProgress: 'પ્રગતિમાં',
    stageResolved: 'ઉકેલાયેલ',
    langName: 'ગુજરાતી'
  },
  bn: {
    brandTagline: 'সরকারি পোর্টাল',
    brandSubtitle: 'জনসেবা প্রদান ও নাগরিক অভিযোগ প্রতিকার ব্যবস্থা',
    searchPlaceholder: 'অভিযোগ, পরিষেবা আইডি বা প্রশ্ন অনুসন্ধান করুন...',
    citizenPortal: 'নাগরিক পোর্টাল',
    adminPortal: 'অফিসার কন্ট্রোল রুম',
    signIn: 'সাইন ইন করুন',
    signOut: 'সাইন আউট',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    lodgeGrievance: 'নতুন অভিযোগ দায়ের করুন',
    overviewTab: 'ড্যাশবোর্ড পর্যালোচনা',
    servicesTab: 'জনসেবা ক্যাটালগ',
    trackTab: 'অবস্থা ও সমাধান ট্র্যাক করুন',
    faqsTab: 'সহায়তা ও এআই গাইড',
    slaCompliance: 'SLA সম্মতি হার',
    resolvedThisMonth: 'এই মাসে নিষ্পত্তিকৃত মামলা',
    totalLodged: 'মোট দায়েরকৃত অভিযোগ',
    inProgress: 'প্রক্রিয়াধীন',
    resolvedCases: 'সফলভাবে সমাধানকৃত',
    urgentAlerts: 'জরুরি সতর্কতা',
    popularServices: 'জনপ্রিয় জনসেবা',
    applyNow: 'এখনই আবেদন করুন',
    recentSubmissions: 'অভিযোগ প্রতিকার তালিকা',
    allWards: 'সমস্ত ওয়ার্ড',
    mySubmissions: 'আমার অভিযোগসমূহ',
    allStatuses: 'সমস্ত স্থিতি',
    trackProgress: 'অগ্রগতি ট্র্যাক করুন',
    needEscalation: 'জরুরি সাহায্য প্রয়োজন?',
    helpline: '24x7 নাগরিক হেল্পলাইন: 1800-425-GOV',
    nodalOfficerControl: 'নোডাল অফিসার কন্ট্রোল ড্যাশবোর্ড',
    publicGovernanceCenter: 'জনসেবা প্রদান ও সুশাসন কেন্দ্র',
    governanceSubtitle: 'রিয়েল-টাইম অভিযোগ পরিচালনা, কর্মকর্তা নিয়োগ এবং SLA পর্যবেক্ষণ।',
    exportCSV: 'CSV রিপোর্ট ডাউনলোড করুন',
    exportAudit: 'অডিট সারাংশ প্রিন্ট করুন',
    awaitingReview: 'পর্যালোচনাধীন',
    activeInField: 'মাঠে সক্রিয়',
    urgentEscalations: 'জরুরি মামলা',
    departmentWorkload: 'বিভাগভিত্তিক অভিযোগের বিবরণ',
    slaTatScorecard: 'বিভাগীয় SLA সমাধান সময় (TAT) স্কোরকার্ড',
    manageTickets: 'অভিযোগ টিকিট পরিচালনা করুন',
    manageTicketsSub: 'কর্মকর্তা নিয়োগ করুন, স্থিতি আপডেট করুন, IPFS প্রমাণ যাচাই করুন',
    serviceAppsQueue: 'জনসেবা আবেদন সারি',
    serviceAppsQueueSub: 'নাগরিক আবেদন পর্যালোচনা করুন এবং সনদপত্র প্রদান করুন',
    grievancesQueue: 'অভিযোগ টিকিট সারি',
    serviceApps: 'জনসেবা আবেদন',
    kbTitle: 'নাগরিক জ্ঞানভাণ্ডার ও প্রশ্নোত্তর',
    kbSubtitle: 'অফিসিয়াল নির্দেশিকা ও এসএলএ সময়সীমা',
    aiBotTitle: 'জনসেবা এআই সহকারী',
    aiBotSub: '২৪x৭ তাৎক্ষণিক সহায়তা বট',
    aiGreeting: 'নমস্কার! আমি জনসেবা এআই সহকারী। যে কোনো প্রশ্ন জিজ্ঞাসা করুন বা টিকিট আইডি দিয়ে স্ট্যাটাস জানুন!',
    askAiPlaceholder: 'এআই-কে জিজ্ঞাসা করুন (উদাঃ জন্ম সনদ পেতে কত দিন লাগে?)',
    quickPrompt1: 'আমার অভিযোগ কীভাবে ট্র্যাক করব?',
    quickPrompt2: 'জন্ম সনদের জন্য কী কী নথি প্রয়োজন?',
    quickPrompt3: 'নিকাশী সমস্যার জন্য SLA সময় কত?',
    quickPrompt4: 'মীমাংসাহীন অভিযোগ কীভাবে পুনরায় খুলব?',
    trackTitle: 'লাইভ অভিযোগ প্রতিকার ও ট্র্যাকিং',
    trackSubtitle: 'রিয়েল-টাইম অগ্রগতি ও ব্লকচেইন যাচাইকরণ',
    enterTrackingId: 'অভিযোগ আইডি লিখুন (উদাঃ GRV-2026-8910)',
    trackButton: 'অবস্থা দেখুন',
    timelineHeader: 'প্রতিকার সময়রেখা',
    ipfsProof: 'IPFS প্রমাণ নথি',
    blockchainProof: 'হাইপারলেজার ফ্যাব্রিক যাচাইকরণ',
    citizenFeedback: 'নাগরিক প্রতিক্রিয়া',
    rateResolution: 'সমাধানের মান মূল্যায়ন করুন',
    submitFeedback: 'প্রতিক্রিয়া জমা দিন',
    reopenTicket: 'সমস্যা মেটেনি? অভিযোগ পুনরায় খুলুন',
    printReceipt: 'রসিদ প্রিন্ট করুন',
    settingsTitle: 'সেটিংস ও পছন্দসমূহ',
    settingsSubtitle: 'ভাষা ও বিজ্ঞপ্তি পরিবর্তন করুন',
    profileTab: 'প্রোফাইল',
    languageTab: 'ভাষা ও রাজ্য',
    appearanceTab: 'চেহারা',
    alertsTab: 'বিজ্ঞপ্তি',
    securityTab: 'নিরাপত্তা',
    saveChanges: 'পরিবর্তন সংরক্ষণ করুন',
    close: 'বন্ধ করুন',
    notifications: 'বিজ্ঞপ্তি',
    clearAll: 'সব মুছুন',
    noNotifications: 'নতুন কোনো বিজ্ঞপ্তি নেই',
    heroTitle: 'জনসেবা প্রদান ও নাগরিক অভিযোগ প্রতিকার',
    heroDesc: 'স্বচ্ছ ও দায়বদ্ধ জনসেবা। অভিযোগ দায়ের করুন ও অগ্রগতি দেখুন।',
    browseServices: 'পরিষেবাসমূহ দেখুন',
    viewAllServices: 'সমস্ত পরিষেবা',
    fee: 'ফি',
    free: 'বিনামূল্যে',
    daysSla: 'দিনের SLA',
    stageSubmitted: 'দায়ের করা হয়েছে',
    stageReview: 'পর্যালোচনাধীন',
    stageAssigned: 'নিয়োগকৃত',
    stageProgress: 'চলমান',
    stageResolved: 'সমাধানকৃত',
    langName: 'বাংলা'
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('janseva_lang') || 'en');

  useEffect(() => {
    localStorage.setItem('janseva_lang', lang);
  }, [lang]);

  const t = (key) => {
    return DICTIONARY[lang]?.[key] || DICTIONARY['en']?.[key] || key;
  };

  const currentLanguageMeta = SUPPORTED_LANGUAGES.find(l => l.code === lang) || SUPPORTED_LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ 
      lang, 
      setLang, 
      t, 
      supportedLanguages: SUPPORTED_LANGUAGES,
      currentLanguageMeta 
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
