import React, { createContext, useContext, useState, useEffect } from 'react';

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', region: 'National / Official' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', region: 'North & Central India' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', region: 'Karnataka' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', region: 'Tamil Nadu & Puducherry' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', region: 'Andhra Pradesh & Telangana' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', region: 'Kerala & Lakshadweep' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', region: 'Maharashtra & Goa' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', region: 'Gujarat & Daman/Diu' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', region: 'West Bengal & Tripura' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', region: 'Odisha' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', region: 'Punjab' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', region: 'Assam & North East' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', region: 'Jammu & Kashmir, Telangana, UP' }
];

const DICTIONARY = {
  en: {
    brandTagline: 'GOV PORTAL',
    brandSubtitle: 'Public Services & Grievance Governance',
    searchPlaceholder: 'Search grievances, service IDs, or FAQs...',
    citizenPortal: 'Citizen',
    adminPortal: 'Official Admin',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    lodgeGrievance: 'Lodge Grievance',
    overviewTab: 'Dashboard Overview',
    servicesTab: 'Public Services Catalog',
    trackTab: 'Track Status & Resolution',
    faqsTab: 'Knowledge Base & AI Guide',
    slaCompliance: 'SLA Compliance Rate',
    resolvedThisMonth: 'Cases Resolved This Month',
    totalLodged: 'Total Lodged',
    inProgress: 'In Progress',
    resolvedCases: 'Successfully Resolved',
    urgentAlerts: 'Urgent Alerts',
    popularServices: 'Popular Public Services',
    applyNow: 'Apply Now',
    recentSubmissions: 'Grievance Tracking & Redressal Stream',
    allWards: 'All Wards',
    mySubmissions: 'My Submissions',
    allStatuses: 'All Statuses',
    trackProgress: 'Track Progress & Timeline',
    needEscalation: 'Need Immediate Escalation?',
    helpline: '24x7 Citizen Helpline: 1800-425-GOV',
    nodalOfficerControl: 'Nodal Officer Control Dashboard',
    publicGovernanceCenter: 'Public Service Delivery Governance Center',
    governanceSubtitle: 'Real-time grievance routing, officer dispatch, SLA tracking, and resolution oversight.',
    exportCSV: 'Export CSV Summary Report',
    exportAudit: 'Print Audit Summary',
    awaitingReview: 'Awaiting Review',
    activeInField: 'Active In Field',
    urgentEscalations: 'Urgent Escalations',
    departmentWorkload: 'Department Grievance Workload Breakdown',
    slaTatScorecard: 'Department SLA Turnaround Time (TAT) Scorecard',
    manageTickets: 'Manage Grievance Tickets',
    manageTicketsSub: 'Assign officers, update status, inspect IPFS evidence, and attach official resolution notes',
    serviceAppsQueue: 'Citizen Public Service Applications Queue',
    serviceAppsQueueSub: 'Review citizen welfare applications, verify identity proofs, and issue approvals',
    grievancesQueue: 'Grievance Tickets Queue',
    serviceApps: 'Public Service Applications',
    langName: 'English'
  },
  hi: {
    brandTagline: 'सरकारी पोर्टल',
    brandSubtitle: 'सार्वजनिक सेवा वितरण एवं नागरिक शिकायत निवारण प्रणाली',
    searchPlaceholder: 'शिकायत, सेवा आईडी या प्रश्न खोजें...',
    citizenPortal: 'नागरिक पोर्टल',
    adminPortal: 'अधिकारी नियंत्रण कक्ष',
    signIn: 'लॉग इन करें',
    signOut: 'लॉग आउट',
    lodgeGrievance: 'नई शिकायत दर्ज करें',
    overviewTab: 'डैशबोर्ड अवलोकन',
    servicesTab: 'सार्वजनिक सेवाएँ',
    trackTab: 'स्थिति और समाधान ट्रैक करें',
    faqsTab: 'सहायता एवं एआई गाइड',
    slaCompliance: 'एसएलए अनुपालन दर',
    resolvedThisMonth: 'इस माह हल किए गए मामले',
    totalLodged: 'कुल दर्ज शिकायतें',
    inProgress: 'प्रगति पर',
    resolvedCases: 'सफलतापूर्वक हल',
    urgentAlerts: 'आपातकालीन अलर्ट',
    popularServices: 'लोकप्रिय सार्वजनिक सेवाएँ',
    applyNow: 'आवेदन करें',
    recentSubmissions: 'नागरिक शिकायत निवारण सूची',
    allWards: 'सभी वार्ड',
    mySubmissions: 'मेरी शिकायतें',
    allStatuses: 'सभी स्थितियाँ',
    trackProgress: 'स्थिति और समयरेखा देखें',
    needEscalation: 'तत्काल सहायता चाहिए?',
    helpline: '24x7 नागरिक हेल्पलाइन: 1800-425-GOV',
    nodalOfficerControl: 'नोडल अधिकारी नियंत्रण कक्ष',
    publicGovernanceCenter: 'लोक सेवा वितरण एवं शासन केंद्र',
    governanceSubtitle: 'वास्तविक समय शिकायत रूटिंग, अधिकारी प्रेषण, एसएलए ट्रैकिंग और समाधान निरीक्षण।',
    exportCSV: 'सीएसवी सारांश रिपोर्ट निर्यात करें',
    exportAudit: 'ऑडिट सारांश प्रिंट करें',
    awaitingReview: 'समीक्षाधीन',
    activeInField: 'फील्ड में सक्रिय',
    urgentEscalations: 'अति आवश्यक मामले',
    departmentWorkload: 'विभागवार शिकायत कार्यभार विवरण',
    slaTatScorecard: 'विभागीय एसएलए टर्नअराउंड समय (टीएटी) स्कोरकार्ड',
    manageTickets: 'शिकायत टिकट प्रबंधित करें',
    manageTicketsSub: 'अधिकारी नियुक्त करें, स्थिति अपडेट करें, आईपीएफएस साक्ष्य जांचें और आधिकारिक नोट जोड़ें',
    serviceAppsQueue: 'नागरिक लोक सेवा आवेदन कतार',
    serviceAppsQueueSub: 'नागरिक कल्याण आवेदनों की समीक्षा करें और स्वीकृतियां जारी करें',
    grievancesQueue: 'शिकायत टिकट कतार',
    serviceApps: 'लोक सेवा आवेदन',
    langName: 'हिन्दी'
  },
  kn: {
    brandTagline: 'ಸರ್ಕಾರಿ ಪೋರ್ಟಲ್',
    brandSubtitle: 'ಸಾರ್ವಜನಿಕ ಸೇವಾ ವಿತರಣೆ ಮತ್ತು ನಾಗರಿಕ ಕುಂದುಕೊರತೆ ನಿರ್ವಹಣೆ',
    searchPlaceholder: 'ದೂರುಗಳು, ಸೇವಾ ಐಡಿ ಅಥವಾ ಪ್ರಶ್ನೆಗಳನ್ನು ಹುಡುಕಿ...',
    citizenPortal: 'ನಾಗರಿಕ ಪೋರ್ಟಲ್',
    adminPortal: 'ಅಧಿಕಾರಿ ನಿಯಂತ್ರಣ ಕೊಠಡಿ',
    signIn: 'ಸೈನ್ ಇನ್',
    signOut: 'ಸೈನ್ ಔಟ್',
    lodgeGrievance: 'ಹೊಸ ದೂರು ದಾಖಲಿಸಿ',
    overviewTab: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಅವಲೋಕನ',
    servicesTab: 'ಸಾರ್ವಜನಿಕ ಸೇವೆಗಳು',
    trackTab: 'ಸ್ಥಿತಿ ಮತ್ತು ಪ್ರಗತಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    faqsTab: 'ಸಹಾಯ ಮತ್ತು AI ಮಾರ್ಗದರ್ಶಿ',
    slaCompliance: 'SLA ಅನುಸರಣಾ ದರ',
    resolvedThisMonth: 'ಈ ತಿಂಗಳು ಪರಿಹರಿಸಲಾದ ಪ್ರಕರಣಗಳು',
    totalLodged: 'ಒಟ್ಟು ದಾಖಲಾದ ದೂರುಗಳು',
    inProgress: 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    resolvedCases: 'ಯಶಸ್ವಿಯಾಗಿ ಪರಿಹರಿಸಲಾಗಿದೆ',
    urgentAlerts: 'ತುರ್ತು ಎಚ್ಚರಿಕೆಗಳು',
    popularServices: 'ಜನಪ್ರಿಯ ಸಾರ್ವಜನಿಕ ಸೇವೆಗಳು',
    applyNow: 'ಈಗಲೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    recentSubmissions: 'ದೂರುಗಳ ಟ್ರ್ಯಾಕಿಂಗ್ ಪಟ್ಟಿ',
    allWards: 'ಎಲ್ಲಾ ವಾರ್ಡ್‌ಗಳು',
    mySubmissions: 'ನನ್ನ ದೂರುಗಳು',
    allStatuses: 'ಎಲ್ಲಾ ಸ್ಥಿತಿಗಳು',
    trackProgress: 'ಪ್ರಗತಿ ಮತ್ತು ಸಮಯರೇಖೆಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    needEscalation: 'ತುರ್ತು ಸಹಾಯ ಬೇಕೇ?',
    helpline: '24x7 ನಾಗರಿಕ ಸಹಾಯವಾಣಿ: 1800-425-GOV',
    nodalOfficerControl: 'ನೋಡಲ್ ಅಧಿಕಾರಿ ನಿಯಂತ್ರಣ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    publicGovernanceCenter: 'ಸಾರ್ವಜನಿಕ ಸೇವಾ ವಿತರಣಾ ಆಡಳಿತ ಕೇಂದ್ರ',
    governanceSubtitle: 'ನೈಜ-ಸಮಯದ ದೂರು ವರ್ಗಾವಣೆ, ಅಧಿಕಾರಿ ನಿಯೋಜನೆ ಮತ್ತು SLA ಪರಿಹಾರ ಮೇಲ್ವಿಚಾರಣೆ.',
    exportCSV: 'CSV ಸಾರಾಂಶ ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    exportAudit: 'ಆಡಿಟ್ ಸಾರಾಂಶ ಮುದ್ರಿಸಿ',
    awaitingReview: 'ಪರಿಶೀಲನೆಗಾಗಿ ಕಾಯುತ್ತಿದೆ',
    activeInField: 'ಕ್ಷೇತ್ರದಲ್ಲಿ ಸಕ್ರಿಯವಾಗಿದೆ',
    urgentEscalations: 'ತುರ್ತು ಪ್ರಕರಣಗಳು',
    departmentWorkload: 'ಇಲಾಖಾವಾರು ದೂರುಗಳ ಕಾರ್ಯಭಾರ ವಿವರ',
    slaTatScorecard: 'ಇಲಾಖಾ SLA ಟರ್ನ್‌ಅರೌಂಡ್ ಸಮಯ (TAT) ಸ್ಕೋರ್‌ಕಾರ್ಡ್',
    manageTickets: 'ದೂರು ಟಿಕೆಟ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    manageTicketsSub: 'ಅಧಿಕಾರಿಗಳನ್ನು ನಿಯೋಜಿಸಿ, ಸ್ಥಿತಿ ನವೀಕರಿಸಿ ಮತ್ತು IPFS ಪುರಾವೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    serviceAppsQueue: 'ಸಾರ್ವಜನಿಕ ಸೇವಾ ಅರ್ಜಿಗಳ ಸಾಲು',
    serviceAppsQueueSub: 'ನಾಗರಿಕ ಅರ್ಜಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಡಿಜಿಟಲ್ ಪ್ರಮಾಣಪತ್ರಗಳನ್ನು ನೀಡಿ',
    grievancesQueue: 'ದೂರುಗಳ ಟಿಕೆಟ್ ಸಾಲು',
    serviceApps: 'ಸಾರ್ವಜನಿಕ ಸೇವಾ ಅರ್ಜಿಗಳು',
    langName: 'ಕನ್ನಡ'
  },
  ta: {
    brandTagline: 'அரசு போர்டல்',
    brandSubtitle: 'பொது சேவை வழங்கல் மற்றும் குடிமக்கள் குறைதீர்க்கும் மேலாண்மை',
    searchPlaceholder: 'புகார்கள், சேவை எண் அல்லது கேள்விகளைத் தேடுங்கள்...',
    citizenPortal: 'குடிமக்கள் போர்டல்',
    adminPortal: 'அதிகாரி கட்டுப்பாட்டு அறை',
    signIn: 'உள்நுழைக',
    signOut: 'வெளியேறு',
    lodgeGrievance: 'புதிய புகார் பதிவு செய்',
    overviewTab: 'டாஷ்போர்டு கண்ணோட்டம்',
    servicesTab: 'பொது சேவைகள் பட்டியல்',
    trackTab: 'நிலையைக் கண்காணிக்கவும்',
    faqsTab: 'உதவி மற்றும் AI வழிகாட்டி',
    slaCompliance: 'SLA இணக்க விகிதம்',
    resolvedThisMonth: 'இம்மாதம் தீர்க்கப்பட்ட புகார்கள்',
    totalLodged: 'மொத்த புகார்கள்',
    inProgress: 'நடவடிக்கையில் உள்ளது',
    resolvedCases: 'வெற்றிகரமாக தீர்க்கப்பட்டது',
    urgentAlerts: 'அவசர எச்சரிக்கைகள்',
    popularServices: 'பிரபலமான பொது சேவைகள்',
    applyNow: 'இப்போதே விண்ணப்பிக்கவும்',
    recentSubmissions: 'புகார் கண்காணிப்பு பட்டியல்',
    allWards: 'அனைத்து வார்டுகள்',
    mySubmissions: 'எனது புகார்கள்',
    allStatuses: 'அனைத்து நிலைகள்',
    trackProgress: 'முன்னேற்றத்தைக் கண்காணிக்கவும்',
    needEscalation: 'உடனடி உதவி தேவையா?',
    helpline: '24x7 குடிமக்கள் உதவி எண்: 1800-425-GOV',
    nodalOfficerControl: 'நோடல் அதிகாரி கட்டுப்பாட்டு மையம்',
    publicGovernanceCenter: 'பொது சேவை வழங்கல் ஆளுகை மையம்',
    governanceSubtitle: 'நிகழ்நேர புகார் பரிமாற்றம், அதிகாரி நியமனம் மற்றும் SLA தீர்வு கண்காணிப்பு.',
    exportCSV: 'CSV அறிக்கை பதிவிறக்கு',
    exportAudit: 'தணிக்கை அறிக்கை அச்சிடு',
    awaitingReview: 'பரிசீலனையில் உள்ளது',
    activeInField: 'களத்தில் செயலில் உள்ளது',
    urgentEscalations: 'அவசர புகார்கள்',
    departmentWorkload: 'துறைவாரி பணிச்சுமை விவரம்',
    slaTatScorecard: 'துறை SLA திருப்புமுனை நேர (TAT) அறிக்கை',
    manageTickets: 'புகார் டிக்கெட்டுகளை நிர்வகிக்கவும்',
    manageTicketsSub: 'அதிகாரிகளை நியமிக்கவும், நிலையை புதுப்பிக்கவும், IPFS ஆதாரங்களை சரிபார்க்கவும்',
    serviceAppsQueue: 'பொது சேவை விண்ணப்பங்கள் வரிசை',
    serviceAppsQueueSub: 'விண்ணப்பங்களை சரிபார்த்து டிஜிட்டல் சான்றிதழ்களை வழங்கவும்',
    grievancesQueue: 'புகார் டிக்கெட் வரிசை',
    serviceApps: 'பொது சேவை விண்ணப்பங்கள்',
    langName: 'தமிழ்'
  },
  te: {
    brandTagline: 'ప్రభుత్వ పోర్టల్',
    brandSubtitle: 'ప్రజా సేవల డెలివరీ మరియు పౌర ఫిర్యాదుల పరిష్కార వ్యవస్థ',
    searchPlaceholder: 'ఫిర్యాదులు, సేవా ఐడీ లేదా ప్రశ్నలను వెతకండి...',
    citizenPortal: 'పౌర పోర్టల్',
    adminPortal: 'అధికారి నియంత్రణ గది',
    signIn: 'సైన్ ఇన్',
    signOut: 'సైన్ అవుట్',
    lodgeGrievance: 'కొత్త ఫిర్యాదు నమోదు చేయండి',
    overviewTab: 'డాష్‌బోర్డ్ అవలోకనం',
    servicesTab: 'ప్రజా సేవల జాబితా',
    trackTab: 'స్థితి మరియు పరిష్కారాన్ని ట్రాక్ చేయండి',
    faqsTab: 'సహాయం మరియు AI గైడ్',
    slaCompliance: 'SLA సమ్మతి రేటు',
    resolvedThisMonth: 'ఈ నెలలో పరిష్కరించబడినవి',
    totalLodged: 'మొత్తం నమోదైనవి',
    inProgress: 'పురోగతిలో ఉంది',
    resolvedCases: 'విజయవంతంగా పరిష్కరించబడింది',
    urgentAlerts: 'అత్యవసర హెచ్చరికలు',
    popularServices: 'ప్రజాదరణ పొందిన సేవలు',
    applyNow: 'ఇప్పుడే దరఖాస్తు చేసుకోండి',
    recentSubmissions: 'ఫిర్యాదుల పర్యవేక్షణ జాబితా',
    allWards: 'అన్ని వార్డులు',
    mySubmissions: 'నా ఫిర్యాదులు',
    allStatuses: 'అన్ని స్థితులు',
    trackProgress: 'పురోగతిని ట్రాక్ చేయండి',
    needEscalation: 'తక్షణ సహాయం కావాలా?',
    helpline: '24x7 పౌర హెల్ప్‌లైన్: 1800-425-GOV',
    nodalOfficerControl: 'నోడల్ ఆఫీసర్ నియంత్రణ డాష్‌బోర్డ్',
    publicGovernanceCenter: 'ప్రజా సేవల డెలివరీ పాలనా కేంద్రం',
    governanceSubtitle: 'రియల్-టైమ్ ఫిర్యాదుల మళ్లింపు, అధికారి కేటాయింపు మరియు SLA పరిష్కార పర్యవేక్షణ.',
    exportCSV: 'CSV నివేదిక డౌన్‌లోడ్',
    exportAudit: 'ఆడిట్ నివేదిక ప్రింట్ చేయండి',
    awaitingReview: 'సమీక్ష కోసం వేచి ఉంది',
    activeInField: 'ఫీల్డ్‌లో క్రియాశీలంగా ఉంది',
    urgentEscalations: 'అత్యవసర కేసులు',
    departmentWorkload: 'విభాగాల వారీగా పనిభారం వివరాలు',
    slaTatScorecard: 'విభాగ SLA టర్నరౌండ్ సమయం (TAT) స్కోర్‌కార్డ్',
    manageTickets: 'ఫిర్యాదు టిక్కెట్లను నిర్వహించండి',
    manageTicketsSub: 'అధికారులను కేటాయించండి, స్థితిని నవీకరించండి, IPFS సాక్ష్యాలను తనిఖీ చేయండి',
    serviceAppsQueue: 'ప్రజా సేవల దరఖాస్తుల క్యూ',
    serviceAppsQueueSub: 'పౌర దరఖాస్తులను ధృవీకరించండి మరియు సర్టిఫికేట్లు జారీ చేయండి',
    grievancesQueue: 'ఫిర్యాదుల క్యూ',
    serviceApps: 'ప్రజా సేవల దరఖాస్తులు',
    langName: 'తెలుగు'
  },
  ml: {
    brandTagline: 'സർക്കാർ പോർട്ടൽ',
    brandSubtitle: 'പൊതു സേവന വിതരണവും പൗര പരാതി പരിഹാര സംവിധാനവും',
    searchPlaceholder: 'പരാതികൾ, സേവന ഐഡി അല്ലെങ്കിൽ ചോദ്യങ്ങൾ തിരയുക...',
    citizenPortal: 'പൗര പോർട്ടൽ',
    adminPortal: 'ഉദ്യോഗസ്ഥ നിയന്ത്രണ മുറി',
    signIn: 'സൈൻ ഇൻ ചെയ്യുക',
    signOut: 'സൈൻ ഔട്ട്',
    lodgeGrievance: 'പരാതി രജിസ്റ്റർ ചെയ്യുക',
    overviewTab: 'ഡാഷ്‌ബോർഡ് അവലോകനം',
    servicesTab: 'പൊതു സേവനങ്ങൾ',
    trackTab: 'സ്ഥിതിഗതികൾ ട്രാക്ക് ചെയ്യുക',
    faqsTab: 'സഹായവും AI ഗൈഡും',
    slaCompliance: 'SLA പാലിക്കൽ നിരക്ക്',
    resolvedThisMonth: 'ഈ മാസം പരിഹരിച്ച കേസുകൾ',
    totalLodged: 'ആകെ ലഭിച്ച പരാതികൾ',
    inProgress: 'നടപടികൾ പുരോഗമിക്കുന്നു',
    resolvedCases: 'വിജയകരമായി പരിഹരിച്ചു',
    urgentAlerts: 'അടിയന്തര മുന്നറിയിപ്പുകൾ',
    popularServices: 'ജനപ്രിയ പൊതു സേവനങ്ങൾ',
    applyNow: 'ഇപ്പോൾ അപേക്ഷിക്കുക',
    recentSubmissions: 'പരാതി പരിഹാര പട്ടിക',
    allWards: 'എല്ലാ വാർഡുകളും',
    mySubmissions: 'എന്റെ പരാതികൾ',
    allStatuses: 'എല്ലാ നിലകളും',
    trackProgress: 'പുരോഗതി പരിശോധിക്കുക',
    needEscalation: 'അടിയന്തര സഹായം ആവശ്യമുണ്ടോ?',
    helpline: '24x7 പൗര ഹെൽപ്പ് ലൈൻ: 1800-425-GOV',
    nodalOfficerControl: 'നോഡൽ ഓഫീസർ കൺട്രോൾ ഡാഷ്‌ബോർഡ്',
    publicGovernanceCenter: 'പൊതുസേവന ഭരണ കേന്ദ്രം',
    governanceSubtitle: 'തത്സമയ പരാതി റൂട്ടിംഗ്, ഉദ്യോഗസ്ഥ നിയോഗം, SLA പരിഹാര മേൽനോട്ടം.',
    exportCSV: 'CSV റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക',
    exportAudit: 'ഓഡിറ്റ് റിപ്പോർട്ട് പ്രിന്റ് ചെയ്യുക',
    awaitingReview: 'പരിശോധനയിലാണ്',
    activeInField: 'ഫീൽഡിൽ സജീവം',
    urgentEscalations: 'അടിയന്തര പരാതികൾ',
    departmentWorkload: 'വകുപ്പ് തിരിച്ചുള്ള ജോലിഭാരം',
    slaTatScorecard: 'വകുപ്പ് SLA ടേൺഎറൗണ്ട് സമയം (TAT) സ്കോർകാർഡ്',
    manageTickets: 'പരാതി ടിക്കറ്റുകൾ കൈകാര്യം ചെയ്യുക',
    manageTicketsSub: 'ഉദ്യോഗസ്ഥരെ ചുമതലപ്പെടുത്തുക, സ്ഥിതി അപ്ഡേറ്റ് ചെയ്യുക, IPFS തെളിവുകൾ പരിശോധിക്കുക',
    serviceAppsQueue: 'സേവന അപേക്ഷകളുടെ ക്യൂ',
    serviceAppsQueueSub: 'അപേക്ഷകൾ പരിശോധിച്ച് ഡിജിറ്റൽ സർട്ടിഫിക്കറ്റുകൾ നൽകുക',
    grievancesQueue: 'പരാതി ടിക്കറ്റ് ക്യൂ',
    serviceApps: 'പൊതു സേവന അപേക്ഷകൾ',
    langName: 'മലയാളം'
  },
  mr: {
    brandTagline: 'शासकीय पोर्टल',
    brandSubtitle: 'सार्वजनिक सेवा वितरण व नागरिक तक्रार निवारण प्रणाली',
    searchPlaceholder: 'तक्रार, सेवा आयडी किंवा प्रश्न शोधा...',
    citizenPortal: 'नागरिक पोर्टल',
    adminPortal: 'अधिकारी नियंत्रण कक्ष',
    signIn: 'साइन इन करा',
    signOut: 'साइन आउट',
    lodgeGrievance: 'नवीन तक्रार नोंदवा',
    overviewTab: 'डॅशबोर्ड विहंगावलोकन',
    servicesTab: 'सार्वजनिक सेवा सूची',
    trackTab: 'स्थिती व निवारण ट्रॅक करा',
    faqsTab: 'मदत व AI मार्गदर्शक',
    slaCompliance: 'SLA पूर्तता दर',
    resolvedThisMonth: 'या महिन्यात सोडवलेली प्रकरणे',
    totalLodged: 'एकूण नोंदवलेल्या तक्रारी',
    inProgress: 'प्रगतीपथावर',
    resolvedCases: 'यशस्वीरीत्या निवारण',
    urgentAlerts: 'तातडीच्या सूचना',
    popularServices: 'लोकप्रिय सार्वजनिक सेवा',
    applyNow: 'आता अर्ज करा',
    recentSubmissions: 'तक्रार निवारण प्रवाह',
    allWards: 'सर्व प्रभाग/वॉर्ड',
    mySubmissions: 'माझ्या तक्रारी',
    allStatuses: 'सर्व स्थिती',
    trackProgress: 'प्रगती व कालमर्यादा ट्रॅक करा',
    needEscalation: 'तातडीची मदत हवी आहे का?',
    helpline: '24x7 नागरिक हेल्पलाइन: 1800-425-GOV',
    nodalOfficerControl: 'नोडल अधिकारी नियंत्रण डॅशबोर्ड',
    publicGovernanceCenter: 'सार्वजनिक सेवा वितरण प्रशासन केंद्र',
    governanceSubtitle: 'रिअल-टाइम तक्रार वाटप, अधिकारी नियुक्ती आणि SLA निवारण पर्यवेक्षण.',
    exportCSV: 'CSV अहवाल डाउनलोड करा',
    exportAudit: 'ऑडिट अहवाल प्रिंट करा',
    awaitingReview: 'पुनरावलोकनाधीन',
    activeInField: 'फील्डवर सक्रिय',
    urgentEscalations: 'तातडीची प्रकरणे',
    departmentWorkload: 'विभागनिहाय तक्रार भार तपशील',
    slaTatScorecard: 'विभागीय SLA निवारण वेळ (TAT) स्कोअरकार्ड',
    manageTickets: 'तक्रार तिकिटे व्यवस्थापित करा',
    manageTicketsSub: 'अधिकारी नियुक्त करा, स्थिती अद्यतनित करा, IPFS पुरावे तपासा',
    serviceAppsQueue: 'सार्वजनिक सेवा अर्ज रांग',
    serviceAppsQueueSub: 'नागरिक अर्जांची पडताळणी करा आणि प्रमाणपत्रे जारी करा',
    grievancesQueue: 'तक्रार तिकिट रांग',
    serviceApps: 'सार्वजनिक सेवा अर्ज',
    langName: 'मराठी'
  },
  gu: {
    brandTagline: 'સરકારી પોર્ટલ',
    brandSubtitle: 'જાહેર સેવા વિતરણ અને નાગરિક ફરિયાદ નિવારણ વ્યવસ્થા',
    searchPlaceholder: 'ફરિયાદ, સેવા આઈડી અથવા પ્રશ્નો શોધો...',
    citizenPortal: 'નાગરિક પોર્ટલ',
    adminPortal: 'અધિકારી કંટ્રોલ રૂમ',
    signIn: 'સાઇન ઇન',
    signOut: 'સાઇન આઉટ',
    lodgeGrievance: 'નવી ફરિયાદ નોંધાવો',
    overviewTab: 'ડેશબોર્ડ ઝાંખી',
    servicesTab: 'જાહેર સેવાઓની યાદી',
    trackTab: 'સ્થિતિ અને નિવારણ ટ્રેક કરો',
    faqsTab: 'સહાય અને AI ગાઇડ',
    slaCompliance: 'SLA પાલન દર',
    resolvedThisMonth: 'આ મહિને ઉકેલાયેલા કેસો',
    totalLodged: 'કુલ નોંધાયેલ ફરિયાદો',
    inProgress: 'પ્રગતિ હેઠળ',
    resolvedCases: 'સફળતાપૂર્વક ઉકેલાયેલ',
    urgentAlerts: 'તાકીદની ચેતવણીઓ',
    popularServices: 'લોકપ્રિય જાહેર સેવાઓ',
    applyNow: 'હમણાં અરજી કરો',
    recentSubmissions: 'ફરિયાદ નિવારણ પ્રવાહ',
    allWards: 'બધા વોર્ડ',
    mySubmissions: 'મારી ફરિયાદો',
    allStatuses: 'બધી સ્થિતિઓ',
    trackProgress: 'પ્રગતિ અને સમયરેખા ટ્રેક કરો',
    needEscalation: 'તાત્કાલિક મદદની જરૂર છે?',
    helpline: '24x7 નાગરિક હેલ્પલાઇન: 1800-425-GOV',
    nodalOfficerControl: 'નોડલ ઓફિસર કંટ્રોલ ડેશબોર્ડ',
    publicGovernanceCenter: 'જાહેર સેવા વિતરણ શાસન કેન્દ્ર',
    governanceSubtitle: 'રીઅલ-ટાઇમ ફરિયાદ રૂટિંગ, અધિકારી નિમણૂક અને SLA ટ્રેકિંગ.',
    exportCSV: 'CSV અહેવાલ ડાઉનલોડ કરો',
    exportAudit: 'ઓડિટ રિપોર્ટ પ્રિન્ટ કરો',
    awaitingReview: 'સમીક્ષા હેઠળ',
    activeInField: 'ફીલ્ડમાં સક્રિય',
    urgentEscalations: 'તાકીદના કેસો',
    departmentWorkload: 'વિભાગવાર કાર્યભાર વિગત',
    slaTatScorecard: 'વિભાગીય SLA ટર્નઅરાઉન્ડ સમય (TAT) સ્કોરકાર્ડ',
    manageTickets: 'ફરિયાદ ટિકિટોનું સંચાલન કરો',
    manageTicketsSub: 'અધિકારીઓની નિમણૂક કરો, સ્થિતિ અપડેટ કરો, IPFS પુરાવા ચકાસો',
    serviceAppsQueue: 'જાહેર સેવા અરજીઓની કતાર',
    serviceAppsQueueSub: 'નાગરિક અરજીઓની ચકાસણી કરો અને પ્રમાણપત્રો જારી કરો',
    grievancesQueue: 'ફરિયાદ ટિકિટ કતાર',
    serviceApps: 'જાહેર સેવા અરજીઓ',
    langName: 'ગુજરાતી'
  },
  bn: {
    brandTagline: 'সরকারি পোর্টাল',
    brandSubtitle: 'জনসেবা প্রদান ও নাগরিক অভিযোগ প্রতিকার ব্যবস্থা',
    searchPlaceholder: 'অভিযোগ, পরিষেবা আইডি বা প্রশ্ন অনুসন্ধান করুন...',
    citizenPortal: 'নাগরিক পোর্টাল',
    adminPortal: 'অফিসার কন্ট্রোল রুম',
    signIn: 'সাইন ইন করুন',
    signOut: 'সাইন আউট',
    lodgeGrievance: 'নতুন অভিযোগ দায়ের করুন',
    overviewTab: 'ড্যাশবোর্ড পর্যালোচনা',
    servicesTab: 'জনসেবা ক্যাটালগ',
    trackTab: 'অবস্থা ও সমাধান ট্র্যাক করুন',
    faqsTab: 'সহায়তা ও এআই গাইড',
    slaCompliance: 'SLA সম্মতি হার',
    resolvedThisMonth: 'এই মাসে নিষ্পত্তিকৃত মামলা',
    totalLodged: 'মোট দায়েরকৃত অভিযোগ',
    inProgress: 'প্রক্রিয়াধীন',
    resolvedCases: 'সফলভাবে সমাধানকৃত',
    urgentAlerts: 'জরুরি সতর্কতা',
    popularServices: 'জনপ্রিয় জনসেবা',
    applyNow: 'এখনই আবেদন করুন',
    recentSubmissions: 'অভিযোগ প্রতিকার তালিকা',
    allWards: 'সমস্ত ওয়ার্ড',
    mySubmissions: 'আমার অভিযোগসমূহ',
    allStatuses: 'সমস্ত স্থিতি',
    trackProgress: 'অগ্রগতি ট্র্যাক করুন',
    needEscalation: 'জরুরি সাহায্য প্রয়োজন?',
    helpline: '24x7 নাগরিক হেল্পলাইন: 1800-425-GOV',
    nodalOfficerControl: 'নোডাল অফিসার কন্ট্রোল ড্যাশবোর্ড',
    publicGovernanceCenter: 'জনসেবা প্রদান ও সুশাসন কেন্দ্র',
    governanceSubtitle: 'রিয়েল-টাইম অভিযোগ পরিচালনা, কর্মকর্তা নিয়োগ এবং SLA পর্যবেক্ষণ।',
    exportCSV: 'CSV রিপোর্ট ডাউনলোড করুন',
    exportAudit: 'অডিট সারাংশ প্রিন্ট করুন',
    awaitingReview: 'পর্যালোচনাধীন',
    activeInField: 'মাঠে সক্রিয়',
    urgentEscalations: 'জরুরি মামলা',
    departmentWorkload: 'বিভাগভিত্তিক অভিযোগের বিবরণ',
    slaTatScorecard: 'বিভাগীয় SLA সমাধান সময় (TAT) স্কোরকার্ড',
    manageTickets: 'অভিযোগ টিকিট পরিচালনা করুন',
    manageTicketsSub: 'কর্মকর্তা নিয়োগ করুন, স্থিতি আপডেট করুন, IPFS প্রমাণ যাচাই করুন',
    serviceAppsQueue: 'জনসেবা আবেদন সারি',
    serviceAppsQueueSub: 'নাগরিক আবেদন পর্যালোচনা করুন এবং সনদপত্র প্রদান করুন',
    grievancesQueue: 'অভিযোগ টিকিট সারি',
    serviceApps: 'জনসেবা আবেদন',
    langName: 'বাংলা'
  },
  or: {
    brandTagline: 'ସରକାରୀ ପୋର୍ଟାଲ',
    brandSubtitle: 'ଜନସେବା ପ୍ରଦାନ ଏବଂ ନାଗରିକ ଅଭିଯୋଗ ନିବାରଣ ବ୍ୟବସ୍ଥା',
    searchPlaceholder: 'ଅଭିଯୋଗ, ସେବା ଆଇଡି କିମ୍ବା ପ୍ରଶ୍ନ ଖୋଜନ୍ତୁ...',
    citizenPortal: 'ନାଗରିକ ପୋର୍ଟାଲ',
    adminPortal: 'ଅଧିକାରୀ ନିୟନ୍ତ୍ରଣ କକ୍ଷ',
    signIn: 'ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    signOut: 'ସାଇନ୍ ଆଉଟ୍',
    lodgeGrievance: 'ନୂଆ ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ',
    overviewTab: 'ଡ୍ୟାସବୋର୍ଡ ସମୀକ୍ଷା',
    servicesTab: 'ଜନସେବା ତାଲିକା',
    trackTab: 'ସ୍ଥିତି ଓ ସମାଧାନ ଟ୍ରାକ୍ କରନ୍ତୁ',
    faqsTab: 'ସହାୟତା ଏବଂ AI ଗାଇଡ୍',
    slaCompliance: 'SLA ଅନୁପାଳନ ହାର',
    resolvedThisMonth: 'ଏହି ମାସରେ ସମାଧାନ ହୋଇଥିବା ମାମଲା',
    totalLodged: 'ମୋଟ ଦାଖଲ ହୋଇଥିବା ଅଭିଯୋଗ',
    inProgress: 'କାର୍ଯ୍ୟ ଚାଲିଛି',
    resolvedCases: 'ସଫଳତାର ସହ ସମାଧାନ',
    urgentAlerts: 'ଜରୁରୀ ସତର୍କତା',
    popularServices: 'ଲୋକପ୍ରିୟ ଜନସେବା',
    applyNow: 'ବର୍ତ୍ତମାନ ଆବେଦନ କରନ୍ତୁ',
    recentSubmissions: 'ଅଭିଯୋଗ ନିବାରଣ ତାଲିକା',
    allWards: 'ସମସ୍ତ ୱାର୍ଡ',
    mySubmissions: 'ମୋର ଅଭିଯୋଗ',
    allStatuses: 'ସମସ୍ତ ସ୍ଥିତି',
    trackProgress: 'ପ୍ରଗତି ଟ୍ରାକ୍ କରନ୍ତୁ',
    needEscalation: 'ଜରୁରୀ ସହାୟତା ଆବଶ୍ୟକ କି?',
    helpline: '24x7 ନାଗରିକ ହେଲ୍ପଲାଇନ୍: 1800-425-GOV',
    nodalOfficerControl: 'ନୋଡାଲ୍ ଅଫିସର କଣ୍ଟ୍ରୋଲ୍ ଡ୍ୟାସବୋର୍ଡ',
    publicGovernanceCenter: 'ଜନସେବା ପ୍ରଦାନ ପ୍ରଶାସନ କେନ୍ଦ୍ର',
    governanceSubtitle: 'ରିଅଲ୍-ଟାଇମ୍ ଅଭିଯୋଗ ପରିଚାଳନା, ଅଧିକାରୀ ନିଯୁକ୍ତି ଏବଂ SLA ତଦାରଖ।',
    exportCSV: 'CSV ରିପୋର୍ଟ ଡାଉନଲୋଡ୍ କରନ୍ତୁ',
    exportAudit: 'ଅଡିଟ୍ ରିପୋର୍ଟ ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
    awaitingReview: 'ସମୀକ୍ଷାଧୀନ',
    activeInField: 'କ୍ଷେତ୍ରରେ ସକ୍ରିୟ',
    urgentEscalations: 'ଜରୁରୀ ମାମଲା',
    departmentWorkload: 'ବିଭାଗ ଅନୁଯାୟୀ କାର୍ଯ୍ୟଭାର ବିବରଣୀ',
    slaTatScorecard: 'ବିଭାଗୀୟ SLA ସମାଧାନ ସମୟ (TAT) ସ୍କୋରକାର୍ଡ',
    manageTickets: 'ଅଭିଯୋଗ ଟିକେଟ ପରିଚାଳନା କରନ୍ତୁ',
    manageTicketsSub: 'ଅଧିକାରୀ ନିଯୁକ୍ତ କରନ୍ତୁ, ସ୍ଥିତି ଅଦ୍ୟତନ କରନ୍ତୁ, IPFS ପ୍ରମାଣ ଯାଞ୍ଚ କରନ୍ତୁ',
    serviceAppsQueue: 'ଜନସେବା ଆବେଦନ ଧାଡ଼ି',
    serviceAppsQueueSub: 'ନାଗରିକ ଆବେଦନ ଯାଞ୍ଚ କରନ୍ତୁ ଏବଂ ପ୍ରମାଣପତ୍ର ପ୍ରଦାନ କରନ୍ତୁ',
    grievancesQueue: 'ଅଭିଯୋଗ ଟିକେଟ ଧାଡ଼ି',
    serviceApps: 'ଜନସେବା ଆବେଦନ',
    langName: 'ଓଡ଼ିଆ'
  },
  pa: {
    brandTagline: 'ਸਰਕਾਰੀ ਪੋਰਟਲ',
    brandSubtitle: 'ਜਨਤਕ ਸੇਵਾ ਵੰਡ ਅਤੇ ਨਾਗਰਿਕ ਸ਼ਿਕਾਇਤ ਨਿਵਾਰਨ ਪ੍ਰਣਾਲੀ',
    searchPlaceholder: 'ਸ਼ਿਕਾਇਤ, ਸੇਵਾ ਆਈਡੀ ਜਾਂ ਸਵਾਲ ਖੋਜੋ...',
    citizenPortal: 'ਨਾਗਰਿਕ ਪੋਰਟਲ',
    adminPortal: 'ਅਧਿਕਾਰੀ ਕੰਟਰੋਲ ਰੂਮ',
    signIn: 'ਸਾਈਨ ਇਨ ਕਰੋ',
    signOut: 'ਸਾਈਨ ਆਊਟ',
    lodgeGrievance: 'ਨਵੀਂ ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',
    overviewTab: 'ਡੈਸ਼ਬੋਰਡ ਸੰਖੇਪ',
    servicesTab: 'ਜਨਤਕ ਸੇਵਾਵਾਂ ਸੂਚੀ',
    trackTab: 'ਸਥਿਤੀ ਅਤੇ ਹੱਲ ਟ੍ਰੈਕ ਕਰੋ',
    faqsTab: 'ਸਹਾਇਤਾ ਅਤੇ AI ਗਾਈਡ',
    slaCompliance: 'SLA ਪਾਲਣਾ ਦਰ',
    resolvedThisMonth: 'ਇਸ ਮਹੀਨੇ ਹੱਲ ਕੀਤੇ ਕੇਸ',
    totalLodged: 'ਕੁੱਲ ਦਰਜ ਸ਼ਿਕਾਇਤਾਂ',
    inProgress: 'ਕਾਰਵਾਈ ਅਧੀਨ',
    resolvedCases: 'ਸਫਲਤਾਪੂਰਵਕ ਹੱਲ',
    urgentAlerts: 'ਜ਼ਰੂਰੀ ਚੇਤਾਵਨੀਆਂ',
    popularServices: 'ਪ੍ਰਸਿੱਧ ਜਨਤਕ ਸੇਵਾਵਾਂ',
    applyNow: 'ਹੁਣੇ ਅਰਜ਼ੀ ਦਿਓ',
    recentSubmissions: 'ਸ਼ਿਕਾਇਤ ਨਿਵਾਰਨ ਸੂਚੀ',
    allWards: 'ਸਾਰੇ ਵਾਰਡ',
    mySubmissions: 'ਮੇਰੀਆਂ ਸ਼ਿਕਾਇਤਾਂ',
    allStatuses: 'ਸਾਰੀਆਂ ਸਥਿਤੀਆਂ',
    trackProgress: 'ਤਰੱਕੀ ਅਤੇ ਸਮਾਂ-ਰੇਖਾ ਟ੍ਰੈਕ ਕਰੋ',
    needEscalation: 'ਤੁਰੰਤ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?',
    helpline: '24x7 ਨਾਗਰਿਕ ਹੈਲਪਲਾਈਨ: 1800-425-GOV',
    nodalOfficerControl: 'ਨੋਡਲ ਅਧਿਕਾਰੀ ਕੰਟਰੋਲ ਡੈਸ਼ਬੋਰਡ',
    publicGovernanceCenter: 'ਜਨਤਕ ਸੇਵਾ ਪ੍ਰਸ਼ਾਸਨ ਕੇਂਦਰ',
    governanceSubtitle: 'ਰੀਅਲ-ਟਾਈਮ ਸ਼ਿਕਾਇਤ ਰੂਟਿੰਗ, ਅਧਿਕਾਰੀ ਨਿਯੁਕਤੀ ਅਤੇ SLA ਨਿਗਰਾਨੀ।',
    exportCSV: 'CSV ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ',
    exportAudit: 'ਆਡਿਟ ਰਿਪੋਰਟ ਪ੍ਰਿੰਟ ਕਰੋ',
    awaitingReview: 'ਸਮੀਖਿਆ ਅਧੀਨ',
    activeInField: 'ਫੀਲਡ ਵਿੱਚ ਸਰਗਰਮ',
    urgentEscalations: 'ਜ਼ਰੂਰੀ ਮਾਮਲੇ',
    departmentWorkload: 'ਵਿਭਾਗ ਵਾਰ ਕੰਮ ਦਾ ਵੇਰਵਾ',
    slaTatScorecard: 'ਵਿਭਾਗੀ SLA ਨਿਪਟਾਰਾ ਸਮਾਂ (TAT) ਸਕੋਰਕਾਰਡ',
    manageTickets: 'ਸ਼ਿਕਾਇਤ ਟਿਕਟਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ',
    manageTicketsSub: 'ਅਧਿਕਾਰੀ ਨਿਯੁਕਤ ਕਰੋ, ਸਥਿਤੀ ਅੱਪਡੇਟ ਕਰੋ, IPFS ਸਬੂਤਾਂ ਦੀ ਜਾਂਚ ਕਰੋ',
    serviceAppsQueue: 'ਜਨਤਕ ਸੇਵਾ ਅਰਜ਼ੀਆਂ ਦੀ ਕਤਾਰ',
    serviceAppsQueueSub: 'ਅਰਜ਼ੀਆਂ ਦੀ ਪੜਤਾਲ ਕਰੋ ਅਤੇ ਸਰਟੀਫਿਕੇਟ ਜਾਰੀ ਕਰੋ',
    grievancesQueue: 'ਸ਼ਿਕਾਇਤ ਟਿਕਟ ਕਤਾਰ',
    serviceApps: 'ਜਨਤਕ ਸੇਵਾ ਅਰਜ਼ੀਆਂ',
    langName: 'ਪੰਜਾਬੀ'
  },
  as: {
    brandTagline: 'চৰকাৰী পৰ্টেল',
    brandSubtitle: 'ৰাজহুৱা সেৱা প্ৰদান আৰু নাগৰিক অভিযোগ নিবাৰণ ব্যৱস্থা',
    searchPlaceholder: 'অভিযোগ, সেৱা আইডি বা প্ৰশ্ন সন্ধান কৰক...',
    citizenPortal: 'নাগৰিক পৰ্টেল',
    adminPortal: 'বিষয়া নিয়ন্ত্ৰণ কক্ষ',
    signIn: 'ছাইন ইন কৰক',
    signOut: 'ছাইন আউট',
    lodgeGrievance: 'নতুন অভিযোগ দাখিল কৰক',
    overviewTab: 'ডেশ্বব’ৰ্ড চমু নিৰীক্ষণ',
    servicesTab: 'ৰাজহুৱা সেৱা তালিকা',
    trackTab: 'স্থিতি আৰু সমাধান ট্ৰেক কৰক',
    faqsTab: 'সহায় আৰু AI নিৰ্দেশিকা',
    slaCompliance: 'SLA অনুসৰণ হাৰ',
    resolvedThisMonth: 'এই মাহত সমাধান হোৱা গোচৰ',
    totalLodged: 'মুঠ দাখিল হোৱা অভিযোগ',
    inProgress: 'প্ৰক্ৰিয়াধীন',
    resolvedCases: 'সফলভাৱে সমাধান কৰা হৈছে',
    urgentAlerts: 'জৰুৰী সতৰ্কতা',
    popularServices: 'জনপ্ৰিয় ৰাজহুৱা সেৱা',
    applyNow: 'এতিয়াই আবেদন কৰক',
    recentSubmissions: 'অভিযোগ নিবাৰণ তালিকা',
    allWards: 'সকলো ৱাৰ্ড',
    mySubmissions: 'মোৰ অভিযোগসমূহ',
    allStatuses: 'সকলো স্থিতি',
    trackProgress: 'অগ্ৰগতি ট্ৰেক কৰক',
    needEscalation: 'জৰুৰী সহায়ৰ প্ৰয়োজন নেকি?',
    helpline: '24x7 নাগৰিক হেল্পলাইন: 1800-425-GOV',
    nodalOfficerControl: 'ন’ডেল বিষয়া নিয়ন্ত্ৰণ ডেশ্বব’ৰ্ড',
    publicGovernanceCenter: 'ৰাজহুৱা সেৱা প্ৰশাসন কেন্দ্ৰ',
    governanceSubtitle: 'বাস্তৱ সময়ৰ অভিযোগ ব্যৱস্থাপনা, বিষয়া নিয়োগ আৰু SLA নিৰীক্ষণ।',
    exportCSV: 'CSV প্ৰতিবেদন ডাউনলোড কৰক',
    exportAudit: 'অডিট প্ৰতিবেদন প্ৰিণ্ট কৰক',
    awaitingReview: 'পুনৰীক্ষণাধীন',
    activeInField: 'ক্ষেত্ৰত সক্ৰিয়',
    urgentEscalations: 'জৰুৰী গোচৰসমূহ',
    departmentWorkload: 'বিভাগীয় কাৰ্যভাৰৰ বিৱৰণ',
    slaTatScorecard: 'বিভাগীয় SLA সমাধান সময় (TAT) স্ক’ৰকাৰ্ড',
    manageTickets: 'অভিযোগ টিকট পৰিচালনা কৰক',
    manageTicketsSub: 'বিষয়া নিযুক্ত কৰক, স্থিতি আপডেট কৰক, IPFS প্ৰমাণ পৰীক্ষা কৰক',
    serviceAppsQueue: 'ৰাজহুৱা সেৱা আবেদনৰ শাৰী',
    serviceAppsQueueSub: 'নাগৰিক আবেদন পৰীক্ষা কৰক আৰু প্ৰমাণপত্ৰ প্ৰদান কৰক',
    grievancesQueue: 'অভিযোগ টিকট শাৰী',
    serviceApps: 'ৰাজহুৱা সেৱা আবেদন',
    langName: 'অসমীয়া'
  },
  ur: {
    brandTagline: 'سرکاری پورٹل',
    brandSubtitle: 'عوامی خدمات کی فراہمی اور شہری شکایات کا ازالہ نظام',
    searchPlaceholder: 'شکایات، سروس آئی ڈی یا سوالات تلاش کریں...',
    citizenPortal: 'شہری پورٹل',
    adminPortal: 'افسر کنٹرول روم',
    signIn: 'سائن ان کریں',
    signOut: 'سائن آؤٹ',
    lodgeGrievance: 'نئی شکایت درج کریں',
    overviewTab: 'ڈیش بورڈ جائزہ',
    servicesTab: 'عوامی خدمات کی فہرست',
    trackTab: 'حیثیت اور پیش رفت ٹریک کریں',
    faqsTab: 'مدد اور AI گائیڈ',
    slaCompliance: 'SLA تعمیل کی شرح',
    resolvedThisMonth: 'اس ماہ حل شدہ کیسز',
    totalLodged: 'کل درج شکایات',
    inProgress: 'زیر کارروائی',
    resolvedCases: 'کامیابی سے حل شدہ',
    urgentAlerts: 'ہنگامی انتباہات',
    popularServices: 'مقبول عوامی خدمات',
    applyNow: 'ابھی درخواست دیں',
    recentSubmissions: 'شکایات کے ازالے کی فہرست',
    allWards: 'تمام وارڈز',
    mySubmissions: 'میری شکایات',
    allStatuses: 'تمام حالتیں',
    trackProgress: 'پیش رفت اور ٹائم لائن ٹریک کریں',
    needEscalation: 'کیا فوری مدد کی ضرورت ہے؟',
    helpline: '24x7 شہری ہیلپ لائن: 1800-425-GOV',
    nodalOfficerControl: 'نوڈل آفیسر کنٹرول ڈیش بورڈ',
    publicGovernanceCenter: 'عوامی خدمات گورننس سینٹر',
    governanceSubtitle: 'ریئل ٹائم شکایات کی ترسیل، افسران کی تعیناتی اور SLA کی نگرانی۔',
    exportCSV: 'CSV رپورٹ ڈاؤن لوڈ کریں',
    exportAudit: 'آڈٹ سمری پرنٹ کریں',
    awaitingReview: 'زیر جائزہ',
    activeInField: 'فیلڈ میں فعال',
    urgentEscalations: 'ہنگامی کیسز',
    departmentWorkload: 'محکمہ جاتی کام کا بوجھ',
    slaTatScorecard: 'محکمہ جاتی SLA حل کا وقت (TAT) اسکور کارڈ',
    manageTickets: 'شکایت ٹکٹس کا انتظام کریں',
    manageTicketsSub: 'افسران تفویض کریں، حیثیت اپ ڈیٹ کریں، IPFS ثبوت چیک کریں',
    serviceAppsQueue: 'عوامی خدمات کی درخواستوں کی قطار',
    serviceAppsQueueSub: 'شہری درخواستوں کی تصدیق کریں اور سرٹیفکیٹ جاری کریں',
    grievancesQueue: 'شکایات ٹکٹ قطار',
    serviceApps: 'عوامی خدمات کی درخواستیں',
    langName: 'اردو'
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('janseva_lang') || 'en');

  useEffect(() => {
    localStorage.setItem('janseva_lang', lang);
  }, [lang]);

  const t = (key) => {
    return DICTIONARY[lang]?.[key] || DICTIONARY['en']?.[key] || key;
  };

  const currentLanguageMeta = SUPPORTED_LANGUAGES.find(l => l.code === lang) || SUPPORTED_LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ 
      lang, 
      setLang, 
      t, 
      supportedLanguages: SUPPORTED_LANGUAGES,
      currentLanguageMeta 
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
