# Dockerfile for Backend (Node.js / Express REST API & Hyperledger Gateway)
FROM node:20-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY . .

EXPOSE 5000
CMD ["node", "index.js"]
